// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsMuteAlarm_screen_init(void)
{
ui_ServiceAlarmsMuteAlarm = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsMuteAlarm, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsMuteAlarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsMuteAlarm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alarms5 = lv_label_create(ui_ServiceAlarmsMuteAlarm);
lv_obj_set_width( ui_Alarms5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Alarms5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Alarms5, 0 );
lv_obj_set_y( ui_Alarms5, -96 );
lv_obj_set_align( ui_Alarms5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Alarms5,"Alarms");
lv_obj_set_style_text_color(ui_Alarms5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Alarms5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Alarms5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Alarms5, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Alarms5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Alarms5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temperature7 = lv_label_create(ui_ServiceAlarmsMuteAlarm);
lv_obj_set_width( ui_Temperature7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature7, -8 );
lv_obj_set_y( ui_Temperature7, -54 );
lv_obj_set_align( ui_Temperature7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature7,"Temperature");
lv_obj_set_style_text_color(ui_Temperature7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temperature7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Temperature7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temperature7, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Battery7 = lv_label_create(ui_ServiceAlarmsMuteAlarm);
lv_obj_set_width( ui_Battery7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Battery7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Battery7, -2 );
lv_obj_set_y( ui_Battery7, -22 );
lv_obj_set_align( ui_Battery7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Battery7,"Battery");
lv_obj_set_style_text_color(ui_Battery7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Battery7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Battery7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Battery7, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lid3 = lv_label_create(ui_ServiceAlarmsMuteAlarm);
lv_obj_set_width( ui_Lid3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Lid3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Lid3, -1 );
lv_obj_set_y( ui_Lid3, 11 );
lv_obj_set_align( ui_Lid3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Lid3,"Lid");
lv_obj_set_style_text_color(ui_Lid3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lid3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Lid3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Lid3, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back27 = lv_label_create(ui_ServiceAlarmsMuteAlarm);
lv_obj_set_width( ui_Back27, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back27, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back27, -10 );
lv_obj_set_y( ui_Back27, 86 );
lv_obj_set_align( ui_Back27, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back27,"Back");
lv_obj_set_style_text_color(ui_Back27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back27, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back27, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back27, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MuteAlarms3 = lv_label_create(ui_ServiceAlarmsMuteAlarm);
lv_obj_set_width( ui_MuteAlarms3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MuteAlarms3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MuteAlarms3, 0 );
lv_obj_set_y( ui_MuteAlarms3, 48 );
lv_obj_set_align( ui_MuteAlarms3, LV_ALIGN_CENTER );
lv_label_set_text(ui_MuteAlarms3,"Mute Alarm");
lv_obj_set_style_text_color(ui_MuteAlarms3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MuteAlarms3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MuteAlarms3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MuteAlarms3, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

}
