// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsTempAlarmDelay_screen_init(void)
{
ui_ServiceAlarmsTempAlarmDelay = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsTempAlarmDelay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsTempAlarmDelay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsTempAlarmDelay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempDeviation2 = lv_label_create(ui_ServiceAlarmsTempAlarmDelay);
lv_obj_set_width( ui_TempDeviation2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempDeviation2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempDeviation2, -4 );
lv_obj_set_y( ui_TempDeviation2, -50 );
lv_obj_set_align( ui_TempDeviation2, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempDeviation2,"Temp Deviation");
lv_obj_set_style_text_color(ui_TempDeviation2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempDeviation2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TempDeviation2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempDeviation2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AlarmDelay1 = lv_label_create(ui_ServiceAlarmsTempAlarmDelay);
lv_obj_set_width( ui_AlarmDelay1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AlarmDelay1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AlarmDelay1, -5 );
lv_obj_set_y( ui_AlarmDelay1, 5 );
lv_obj_set_align( ui_AlarmDelay1, LV_ALIGN_CENTER );
lv_label_set_text(ui_AlarmDelay1,"Alarm Delay");
lv_obj_set_style_text_color(ui_AlarmDelay1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AlarmDelay1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AlarmDelay1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AlarmDelay1, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back20 = lv_label_create(ui_ServiceAlarmsTempAlarmDelay);
lv_obj_set_width( ui_Back20, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back20, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back20, -10 );
lv_obj_set_y( ui_Back20, 59 );
lv_obj_set_align( ui_Back20, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back20,"Back");
lv_obj_set_style_text_color(ui_Back20, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back20, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back20, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back20, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
