// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsTempDelaySet_screen_init(void)
{
ui_ServiceAlarmsTempDelaySet = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsTempDelaySet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsTempDelaySet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsTempDelaySet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_AlarmDelay2 = lv_label_create(ui_ServiceAlarmsTempDelaySet);
lv_obj_set_width( ui_AlarmDelay2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_AlarmDelay2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_AlarmDelay2, -6 );
lv_obj_set_y( ui_AlarmDelay2, -71 );
lv_obj_set_align( ui_AlarmDelay2, LV_ALIGN_CENTER );
lv_label_set_text(ui_AlarmDelay2,"Alarm Delay");
lv_obj_set_style_text_color(ui_AlarmDelay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_AlarmDelay2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_AlarmDelay2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_AlarmDelay2, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DelayTime1 = lv_label_create(ui_ServiceAlarmsTempDelaySet);
lv_obj_set_width( ui_DelayTime1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DelayTime1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DelayTime1, -7 );
lv_obj_set_y( ui_DelayTime1, 0 );
lv_obj_set_align( ui_DelayTime1, LV_ALIGN_CENTER );
lv_label_set_text(ui_DelayTime1,"4 mins");
lv_obj_set_style_text_color(ui_DelayTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DelayTime1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DelayTime1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DelayTime1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DelayTime2 = lv_label_create(ui_ServiceAlarmsTempDelaySet);
lv_obj_set_width( ui_DelayTime2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DelayTime2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DelayTime2, -3 );
lv_obj_set_y( ui_DelayTime2, 37 );
lv_obj_set_align( ui_DelayTime2, LV_ALIGN_CENTER );
lv_label_set_text(ui_DelayTime2,"3 mins");
lv_obj_set_style_text_color(ui_DelayTime2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DelayTime2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DelayTime2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DelayTime2, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DelayTime3 = lv_label_create(ui_ServiceAlarmsTempDelaySet);
lv_obj_set_width( ui_DelayTime3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DelayTime3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DelayTime3, -3 );
lv_obj_set_y( ui_DelayTime3, 73 );
lv_obj_set_align( ui_DelayTime3, LV_ALIGN_CENTER );
lv_label_set_text(ui_DelayTime3,"2 mins");
lv_obj_set_style_text_color(ui_DelayTime3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DelayTime3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DelayTime3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DelayTime3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
