// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingDateTimeHour_screen_init(void)
{
ui_SettingDateTimeHour = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingDateTimeHour, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingDateTimeHour, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingDateTimeHour, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetYear3 = lv_label_create(ui_SettingDateTimeHour);
lv_obj_set_width( ui_SetYear3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetYear3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetYear3, 2 );
lv_obj_set_y( ui_SetYear3, -85 );
lv_obj_set_align( ui_SetYear3, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetYear3,"Set Year: 2023");
lv_obj_set_style_text_color(ui_SetYear3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetYear3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetYear3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetYear3, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetMonth3 = lv_label_create(ui_SettingDateTimeHour);
lv_obj_set_width( ui_SetMonth3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetMonth3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetMonth3, 0 );
lv_obj_set_y( ui_SetMonth3, -54 );
lv_obj_set_align( ui_SetMonth3, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetMonth3,"Set Month: 06");
lv_obj_set_style_text_color(ui_SetMonth3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetMonth3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetMonth3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetMonth3, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetDay3 = lv_label_create(ui_SettingDateTimeHour);
lv_obj_set_width( ui_SetDay3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetDay3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetDay3, -1 );
lv_obj_set_y( ui_SetDay3, -24 );
lv_obj_set_align( ui_SetDay3, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetDay3,"Set Day: 06");
lv_obj_set_style_text_color(ui_SetDay3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetDay3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetDay3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetDay3, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back8 = lv_label_create(ui_SettingDateTimeHour);
lv_obj_set_width( ui_Back8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back8, -8 );
lv_obj_set_y( ui_Back8, 84 );
lv_obj_set_align( ui_Back8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back8,"Back");
lv_obj_set_style_text_color(ui_Back8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back8, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetHour3 = lv_label_create(ui_SettingDateTimeHour);
lv_obj_set_width( ui_SetHour3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetHour3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetHour3, -4 );
lv_obj_set_y( ui_SetHour3, 14 );
lv_obj_set_align( ui_SetHour3, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetHour3,"Set Hour: 06");
lv_obj_set_style_text_color(ui_SetHour3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetHour3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetHour3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetHour3, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetMinute3 = lv_label_create(ui_SettingDateTimeHour);
lv_obj_set_width( ui_SetMinute3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetMinute3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetMinute3, -3 );
lv_obj_set_y( ui_SetMinute3, 52 );
lv_obj_set_align( ui_SetMinute3, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetMinute3,"Set Minute: 06");
lv_obj_set_style_text_color(ui_SetMinute3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetMinute3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetMinute3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetMinute3, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
