// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceDataLoggingBack_screen_init(void)
{
ui_ServiceDataLoggingBack = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceDataLoggingBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceDataLoggingBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceDataLoggingBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DataLogging4 = lv_label_create(ui_ServiceDataLoggingBack);
lv_obj_set_width( ui_DataLogging4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DataLogging4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DataLogging4, 3 );
lv_obj_set_y( ui_DataLogging4, -78 );
lv_obj_set_align( ui_DataLogging4, LV_ALIGN_CENTER );
lv_label_set_text(ui_DataLogging4,"Mute Duration");
lv_obj_set_style_text_color(ui_DataLogging4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DataLogging4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DataLogging4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DataLogging4, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DataLogging4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DataLogging4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LoggingInterval2 = lv_label_create(ui_ServiceDataLoggingBack);
lv_obj_set_width( ui_LoggingInterval2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoggingInterval2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoggingInterval2, 3 );
lv_obj_set_y( ui_LoggingInterval2, -2 );
lv_obj_set_align( ui_LoggingInterval2, LV_ALIGN_CENTER );
lv_label_set_text(ui_LoggingInterval2,"Logging Interval");
lv_obj_set_style_text_color(ui_LoggingInterval2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LoggingInterval2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LoggingInterval2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LoggingInterval2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back33 = lv_label_create(ui_ServiceDataLoggingBack);
lv_obj_set_width( ui_Back33, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back33, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back33, -2 );
lv_obj_set_y( ui_Back33, 44 );
lv_obj_set_align( ui_Back33, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back33,"Back");
lv_obj_set_style_text_color(ui_Back33, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back33, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back33, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back33, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

}
