// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceDataLoggingEnter_screen_init(void)
{
ui_ServiceDataLoggingEnter = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceDataLoggingEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceDataLoggingEnter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceDataLoggingEnter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DataLogging3 = lv_label_create(ui_ServiceDataLoggingEnter);
lv_obj_set_width( ui_DataLogging3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DataLogging3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DataLogging3, 3 );
lv_obj_set_y( ui_DataLogging3, -78 );
lv_obj_set_align( ui_DataLogging3, LV_ALIGN_CENTER );
lv_label_set_text(ui_DataLogging3,"Mute Duration");
lv_obj_set_style_text_color(ui_DataLogging3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DataLogging3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DataLogging3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DataLogging3, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_DataLogging3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_DataLogging3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LoggingInterval = lv_label_create(ui_ServiceDataLoggingEnter);
lv_obj_set_width( ui_LoggingInterval, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoggingInterval, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoggingInterval, 3 );
lv_obj_set_y( ui_LoggingInterval, -2 );
lv_obj_set_align( ui_LoggingInterval, LV_ALIGN_CENTER );
lv_label_set_text(ui_LoggingInterval,"Logging Interval");
lv_obj_set_style_text_color(ui_LoggingInterval, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LoggingInterval, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LoggingInterval, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LoggingInterval, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back32 = lv_label_create(ui_ServiceDataLoggingEnter);
lv_obj_set_width( ui_Back32, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back32, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back32, -2 );
lv_obj_set_y( ui_Back32, 44 );
lv_obj_set_align( ui_Back32, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back32,"Back");
lv_obj_set_style_text_color(ui_Back32, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back32, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back32, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back32, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
