// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsBatteryAlarmBack_screen_init(void)
{
ui_ServiceAlarmsBatteryAlarmBack = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsBatteryAlarmBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsBatteryAlarmBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsBatteryAlarmBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatteryAlarm2 = lv_label_create(ui_ServiceAlarmsBatteryAlarmBack);
lv_obj_set_width( ui_BatteryAlarm2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryAlarm2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryAlarm2, 3 );
lv_obj_set_y( ui_BatteryAlarm2, -78 );
lv_obj_set_align( ui_BatteryAlarm2, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatteryAlarm2,"Battery Alarm");
lv_obj_set_style_text_color(ui_BatteryAlarm2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatteryAlarm2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BatteryAlarm2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatteryAlarm2, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_BatteryAlarm2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_BatteryAlarm2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Battery5 = lv_label_create(ui_ServiceAlarmsBatteryAlarmBack);
lv_obj_set_width( ui_Battery5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Battery5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Battery5, -2 );
lv_obj_set_y( ui_Battery5, -1 );
lv_obj_set_align( ui_Battery5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Battery5,"20%");
lv_obj_set_style_text_color(ui_Battery5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Battery5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Battery5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Battery5, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back25 = lv_label_create(ui_ServiceAlarmsBatteryAlarmBack);
lv_obj_set_width( ui_Back25, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back25, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back25, -2 );
lv_obj_set_y( ui_Back25, 44 );
lv_obj_set_align( ui_Back25, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back25,"Back");
lv_obj_set_style_text_color(ui_Back25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back25, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back25, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back25, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

}
