// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceCalibrationBack_screen_init(void)
{
ui_ServiceCalibrationBack = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceCalibrationBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceCalibrationBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceCalibrationBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Calibrartion5 = lv_label_create(ui_ServiceCalibrationBack);
lv_obj_set_width( ui_Calibrartion5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Calibrartion5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Calibrartion5, 3 );
lv_obj_set_y( ui_Calibrartion5, -78 );
lv_obj_set_align( ui_Calibrartion5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Calibrartion5,"Calibrartion");
lv_obj_set_style_text_color(ui_Calibrartion5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Calibrartion5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Calibrartion5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Calibrartion5, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Calibrartion5, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Calibrartion5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperOffset3 = lv_label_create(ui_ServiceCalibrationBack);
lv_obj_set_width( ui_TemperOffset3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperOffset3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperOffset3, 3 );
lv_obj_set_y( ui_TemperOffset3, -2 );
lv_obj_set_align( ui_TemperOffset3, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperOffset3,"Temper Offset");
lv_obj_set_style_text_color(ui_TemperOffset3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperOffset3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperOffset3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperOffset3, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back36 = lv_label_create(ui_ServiceCalibrationBack);
lv_obj_set_width( ui_Back36, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back36, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back36, -2 );
lv_obj_set_y( ui_Back36, 44 );
lv_obj_set_align( ui_Back36, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back36,"Back");
lv_obj_set_style_text_color(ui_Back36, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back36, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back36, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back36, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

}
