// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceTemperatureFeezerBack_screen_init(void)
{
ui_ServiceTemperatureFeezerBack = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceTemperatureFeezerBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceTemperatureFeezerBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceTemperatureFeezerBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FreezerManu3 = lv_label_create(ui_ServiceTemperatureFeezerBack);
lv_obj_set_width( ui_FreezerManu3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FreezerManu3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FreezerManu3, 0 );
lv_obj_set_y( ui_FreezerManu3, -96 );
lv_obj_set_align( ui_FreezerManu3, LV_ALIGN_CENTER );
lv_label_set_text(ui_FreezerManu3,"Freezer");
lv_obj_set_style_text_color(ui_FreezerManu3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FreezerManu3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_FreezerManu3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FreezerManu3, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FreezerManu3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FreezerManu3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetPoint5 = lv_label_create(ui_ServiceTemperatureFeezerBack);
lv_obj_set_width( ui_SetPoint5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetPoint5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetPoint5, -1 );
lv_obj_set_y( ui_SetPoint5, -48 );
lv_obj_set_align( ui_SetPoint5, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetPoint5,"Set Point");
lv_obj_set_style_text_color(ui_SetPoint5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetPoint5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetPoint5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetPoint5, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue9 = lv_label_create(ui_ServiceTemperatureFeezerBack);
lv_obj_set_width( ui_TemperatureValue9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue9, -4 );
lv_obj_set_y( ui_TemperatureValue9, 13 );
lv_obj_set_align( ui_TemperatureValue9, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue9,"-21°C");
lv_obj_set_style_text_color(ui_TemperatureValue9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue9, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back16 = lv_label_create(ui_ServiceTemperatureFeezerBack);
lv_obj_set_width( ui_Back16, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back16, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back16, -4 );
lv_obj_set_y( ui_Back16, 51 );
lv_obj_set_align( ui_Back16, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back16,"Back");
lv_obj_set_style_text_color(ui_Back16, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back16, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back16, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back16, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

}
