// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceTemperatureFridgeBack_screen_init(void)
{
ui_ServiceTemperatureFridgeBack = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceTemperatureFridgeBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceTemperatureFridgeBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceTemperatureFridgeBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FridgeManu2 = lv_label_create(ui_ServiceTemperatureFridgeBack);
lv_obj_set_width( ui_FridgeManu2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FridgeManu2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FridgeManu2, 0 );
lv_obj_set_y( ui_FridgeManu2, -96 );
lv_obj_set_align( ui_FridgeManu2, LV_ALIGN_CENTER );
lv_label_set_text(ui_FridgeManu2,"Fridge");
lv_obj_set_style_text_color(ui_FridgeManu2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FridgeManu2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_FridgeManu2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FridgeManu2, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FridgeManu2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FridgeManu2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetPoint2 = lv_label_create(ui_ServiceTemperatureFridgeBack);
lv_obj_set_width( ui_SetPoint2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetPoint2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetPoint2, -1 );
lv_obj_set_y( ui_SetPoint2, -48 );
lv_obj_set_align( ui_SetPoint2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetPoint2,"Set Point");
lv_obj_set_style_text_color(ui_SetPoint2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetPoint2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetPoint2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetPoint2, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue4 = lv_label_create(ui_ServiceTemperatureFridgeBack);
lv_obj_set_width( ui_TemperatureValue4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue4, -4 );
lv_obj_set_y( ui_TemperatureValue4, 13 );
lv_obj_set_align( ui_TemperatureValue4, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue4,"4°C");
lv_obj_set_style_text_color(ui_TemperatureValue4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back14 = lv_label_create(ui_ServiceTemperatureFridgeBack);
lv_obj_set_width( ui_Back14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back14, -4 );
lv_obj_set_y( ui_Back14, 51 );
lv_obj_set_align( ui_Back14, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back14,"Back");
lv_obj_set_style_text_color(ui_Back14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back14, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back14, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

}
