// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceTemperatureFreezeSetpoint_screen_init(void)
{
ui_ServiceTemperatureFreezeSetpoint = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceTemperatureFreezeSetpoint, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceTemperatureFreezeSetpoint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceTemperatureFreezeSetpoint, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FreezerManu = lv_label_create(ui_ServiceTemperatureFreezeSetpoint);
lv_obj_set_width( ui_FreezerManu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FreezerManu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FreezerManu, 0 );
lv_obj_set_y( ui_FreezerManu, -96 );
lv_obj_set_align( ui_FreezerManu, LV_ALIGN_CENTER );
lv_label_set_text(ui_FreezerManu,"Freezer");
lv_obj_set_style_text_color(ui_FreezerManu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FreezerManu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_FreezerManu, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FreezerManu, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FreezerManu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FreezerManu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetPoint3 = lv_label_create(ui_ServiceTemperatureFreezeSetpoint);
lv_obj_set_width( ui_SetPoint3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetPoint3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetPoint3, -1 );
lv_obj_set_y( ui_SetPoint3, -48 );
lv_obj_set_align( ui_SetPoint3, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetPoint3,"Set Point");
lv_obj_set_style_text_color(ui_SetPoint3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetPoint3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetPoint3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetPoint3, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue5 = lv_label_create(ui_ServiceTemperatureFreezeSetpoint);
lv_obj_set_width( ui_TemperatureValue5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue5, -4 );
lv_obj_set_y( ui_TemperatureValue5, 8 );
lv_obj_set_align( ui_TemperatureValue5, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue5,"-21°C");
lv_obj_set_style_text_color(ui_TemperatureValue5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue5, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back15 = lv_label_create(ui_ServiceTemperatureFreezeSetpoint);
lv_obj_set_width( ui_Back15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back15, -4 );
lv_obj_set_y( ui_Back15, 51 );
lv_obj_set_align( ui_Back15, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back15,"Back");
lv_obj_set_style_text_color(ui_Back15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back15, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
