format_version: v1.0
configName: Pic32mk_harmony
folderName: Pic32mk_harmony
frameworkPath: E:\Job work\Firmware\PIC\code working
processor: PIC32MK1024GPD064
projectName: Pic32mk_harmony
settings:
  PackageFilter: ''
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  TRUSTZONE: 'false'
  CMSISPath: dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: dev_packs\Microchip\PIC32MK-GP_DFP\1.6.144\atdf\PIC32MK1024GPD064.atdf
