// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_Main_screen_init(void)
{
ui_Main = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Main, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Main, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Main, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SpeakerSymbol = lv_label_create(ui_Main);
lv_obj_set_width( ui_SpeakerSymbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SpeakerSymbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SpeakerSymbol, -126 );
lv_obj_set_y( ui_SpeakerSymbol, -89 );
lv_obj_set_align( ui_SpeakerSymbol, LV_ALIGN_CENTER );
lv_label_set_text(ui_SpeakerSymbol,"O");
lv_obj_set_style_text_color(ui_SpeakerSymbol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SpeakerSymbol, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SpeakerSymbol, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_temper = lv_label_create(ui_Main);
lv_obj_set_width( ui_temper, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temper, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_temper, 103 );
lv_obj_set_y( ui_temper, -89 );
lv_obj_set_align( ui_temper, LV_ALIGN_CENTER );
lv_label_set_text(ui_temper,"-20°C");
lv_obj_set_style_text_color(ui_temper, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_temper, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_temper, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freezer5 = lv_label_create(ui_Main);
lv_obj_set_width( ui_Freezer5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Freezer5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Freezer5, -2 );
lv_obj_set_y( ui_Freezer5, -18 );
lv_obj_set_align( ui_Freezer5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Freezer5,"Freezer");
lv_obj_set_style_text_color(ui_Freezer5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freezer5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Freezer5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Freezer5, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ac = lv_label_create(ui_Main);
lv_obj_set_width( ui_ac, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_ac, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_ac, -104 );
lv_obj_set_y( ui_ac, 63 );
lv_obj_set_align( ui_ac, LV_ALIGN_CENTER );
lv_label_set_text(ui_ac,"AC");
lv_obj_set_style_text_color(ui_ac, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ac, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ac, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatSymbol = lv_label_create(ui_Main);
lv_obj_set_width( ui_BatSymbol, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatSymbol, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatSymbol, 33 );
lv_obj_set_y( ui_BatSymbol, 59 );
lv_obj_set_align( ui_BatSymbol, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatSymbol,LV_SYMBOL_BATTERY_EMPTY);
lv_obj_set_style_text_color(ui_BatSymbol, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatSymbol, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BatSymbol, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatSymbol, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

}
