// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceTemperatureFridge_screen_init(void)
{
ui_ServiceTemperatureFridge = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceTemperatureFridge, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceTemperatureFridge, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceTemperatureFridge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temperature2 = lv_label_create(ui_ServiceTemperatureFridge);
lv_obj_set_width( ui_Temperature2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature2, 0 );
lv_obj_set_y( ui_Temperature2, -96 );
lv_obj_set_align( ui_Temperature2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature2,"Temperature");
lv_obj_set_style_text_color(ui_Temperature2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temperature2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Temperature2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temperature2, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Temperature2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Temperature2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Fridge4 = lv_label_create(ui_ServiceTemperatureFridge);
lv_obj_set_width( ui_Fridge4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Fridge4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Fridge4, -1 );
lv_obj_set_y( ui_Fridge4, -28 );
lv_obj_set_align( ui_Fridge4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Fridge4,"Fridge");
lv_obj_set_style_text_color(ui_Fridge4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Fridge4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Fridge4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Fridge4, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freezer4 = lv_label_create(ui_ServiceTemperatureFridge);
lv_obj_set_width( ui_Freezer4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Freezer4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Freezer4, -5 );
lv_obj_set_y( ui_Freezer4, 14 );
lv_obj_set_align( ui_Freezer4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Freezer4,"Freezer");
lv_obj_set_style_text_color(ui_Freezer4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freezer4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Freezer4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Freezer4, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back12 = lv_label_create(ui_ServiceTemperatureFridge);
lv_obj_set_width( ui_Back12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back12, -4 );
lv_obj_set_y( ui_Back12, 51 );
lv_obj_set_align( ui_Back12, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back12,"Back");
lv_obj_set_style_text_color(ui_Back12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back12, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
