// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarms_screen_init(void)
{
ui_ServiceAlarms = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarms, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarms, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarms, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Service1 = lv_label_create(ui_ServiceAlarms);
lv_obj_set_width( ui_Service1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Service1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Service1, 0 );
lv_obj_set_y( ui_Service1, -96 );
lv_obj_set_align( ui_Service1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Service1,"Service");
lv_obj_set_style_text_color(ui_Service1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Service1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Service1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Service1, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Service1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Service1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temperature3 = lv_label_create(ui_ServiceAlarms);
lv_obj_set_width( ui_Temperature3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature3, -7 );
lv_obj_set_y( ui_Temperature3, -49 );
lv_obj_set_align( ui_Temperature3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature3,"Temperature");
lv_obj_set_style_text_color(ui_Temperature3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temperature3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Temperature3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temperature3, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alarms1 = lv_label_create(ui_ServiceAlarms);
lv_obj_set_width( ui_Alarms1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Alarms1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Alarms1, -1 );
lv_obj_set_y( ui_Alarms1, -12 );
lv_obj_set_align( ui_Alarms1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Alarms1,"Alarms");
lv_obj_set_style_text_color(ui_Alarms1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Alarms1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Alarms1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Alarms1, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back17 = lv_label_create(ui_ServiceAlarms);
lv_obj_set_width( ui_Back17, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back17, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back17, -10 );
lv_obj_set_y( ui_Back17, 86 );
lv_obj_set_align( ui_Back17, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back17,"Back");
lv_obj_set_style_text_color(ui_Back17, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back17, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back17, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back17, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DataLogging1 = lv_label_create(ui_ServiceAlarms);
lv_obj_set_width( ui_DataLogging1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DataLogging1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DataLogging1, -1 );
lv_obj_set_y( ui_DataLogging1, 23 );
lv_obj_set_align( ui_DataLogging1, LV_ALIGN_CENTER );
lv_label_set_text(ui_DataLogging1,"Data Logging");
lv_obj_set_style_text_color(ui_DataLogging1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DataLogging1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DataLogging1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DataLogging1, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Calibrartion1 = lv_label_create(ui_ServiceAlarms);
lv_obj_set_width( ui_Calibrartion1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Calibrartion1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Calibrartion1, -1 );
lv_obj_set_y( ui_Calibrartion1, 54 );
lv_obj_set_align( ui_Calibrartion1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Calibrartion1,"Calibrartion");
lv_obj_set_style_text_color(ui_Calibrartion1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Calibrartion1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Calibrartion1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Calibrartion1, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
