// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingDateTimeDay_screen_init(void)
{
ui_SettingDateTimeDay = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingDateTimeDay, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingDateTimeDay, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingDateTimeDay, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetYear2 = lv_label_create(ui_SettingDateTimeDay);
lv_obj_set_width( ui_SetYear2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetYear2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetYear2, 2 );
lv_obj_set_y( ui_SetYear2, -85 );
lv_obj_set_align( ui_SetYear2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetYear2,"Set Year: 2023");
lv_obj_set_style_text_color(ui_SetYear2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetYear2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetYear2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetYear2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetMonth2 = lv_label_create(ui_SettingDateTimeDay);
lv_obj_set_width( ui_SetMonth2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetMonth2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetMonth2, 0 );
lv_obj_set_y( ui_SetMonth2, -54 );
lv_obj_set_align( ui_SetMonth2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetMonth2,"Set Month: 06");
lv_obj_set_style_text_color(ui_SetMonth2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetMonth2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetMonth2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetMonth2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetDay2 = lv_label_create(ui_SettingDateTimeDay);
lv_obj_set_width( ui_SetDay2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetDay2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetDay2, -1 );
lv_obj_set_y( ui_SetDay2, -17 );
lv_obj_set_align( ui_SetDay2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetDay2,"Set Day: 06");
lv_obj_set_style_text_color(ui_SetDay2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetDay2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetDay2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetDay2, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back7 = lv_label_create(ui_SettingDateTimeDay);
lv_obj_set_width( ui_Back7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back7, -8 );
lv_obj_set_y( ui_Back7, 84 );
lv_obj_set_align( ui_Back7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back7,"Back");
lv_obj_set_style_text_color(ui_Back7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back7, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetHour2 = lv_label_create(ui_SettingDateTimeDay);
lv_obj_set_width( ui_SetHour2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetHour2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetHour2, -4 );
lv_obj_set_y( ui_SetHour2, 19 );
lv_obj_set_align( ui_SetHour2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetHour2,"Set Hour: 06");
lv_obj_set_style_text_color(ui_SetHour2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetHour2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetHour2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetHour2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetMinute2 = lv_label_create(ui_SettingDateTimeDay);
lv_obj_set_width( ui_SetMinute2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetMinute2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetMinute2, -3 );
lv_obj_set_y( ui_SetMinute2, 52 );
lv_obj_set_align( ui_SetMinute2, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetMinute2,"Set Minute: 06");
lv_obj_set_style_text_color(ui_SetMinute2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetMinute2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetMinute2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetMinute2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
