// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceTemperatureFreezer_screen_init(void)
{
ui_ServiceTemperatureFreezer = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceTemperatureFreezer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceTemperatureFreezer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceTemperatureFreezer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temperature1 = lv_label_create(ui_ServiceTemperatureFreezer);
lv_obj_set_width( ui_Temperature1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature1, 0 );
lv_obj_set_y( ui_Temperature1, -96 );
lv_obj_set_align( ui_Temperature1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature1,"Temperature");
lv_obj_set_style_text_color(ui_Temperature1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temperature1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Temperature1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temperature1, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Temperature1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Temperature1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Fridge3 = lv_label_create(ui_ServiceTemperatureFreezer);
lv_obj_set_width( ui_Fridge3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Fridge3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Fridge3, -1 );
lv_obj_set_y( ui_Fridge3, -29 );
lv_obj_set_align( ui_Fridge3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Fridge3,"Fridge");
lv_obj_set_style_text_color(ui_Fridge3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Fridge3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Fridge3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Fridge3, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freezer3 = lv_label_create(ui_ServiceTemperatureFreezer);
lv_obj_set_width( ui_Freezer3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Freezer3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Freezer3, -7 );
lv_obj_set_y( ui_Freezer3, 10 );
lv_obj_set_align( ui_Freezer3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Freezer3,"Freezer");
lv_obj_set_style_text_color(ui_Freezer3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freezer3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Freezer3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Freezer3, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back11 = lv_label_create(ui_ServiceTemperatureFreezer);
lv_obj_set_width( ui_Back11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back11, -4 );
lv_obj_set_y( ui_Back11, 51 );
lv_obj_set_align( ui_Back11, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back11,"Back");
lv_obj_set_style_text_color(ui_Back11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back11, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
