// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingDateTime_screen_init(void)
{
ui_SettingDateTime = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingDateTime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingDateTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingDateTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Settings = lv_label_create(ui_SettingDateTime);
lv_obj_set_width( ui_Settings, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Settings, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Settings, 0 );
lv_obj_set_y( ui_Settings, -96 );
lv_obj_set_align( ui_Settings, LV_ALIGN_CENTER );
lv_label_set_text(ui_Settings,"Settings");
lv_obj_set_style_text_color(ui_Settings, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Settings, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Settings, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Settings, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Settings, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateTime = lv_label_create(ui_SettingDateTime);
lv_obj_set_width( ui_DateTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DateTime, 3 );
lv_obj_set_y( ui_DateTime, -31 );
lv_obj_set_align( ui_DateTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateTime,"Date/Time");
lv_obj_set_style_text_color(ui_DateTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DateTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DateTime, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DateTime, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DownloadData = lv_label_create(ui_SettingDateTime);
lv_obj_set_width( ui_DownloadData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DownloadData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DownloadData, 0 );
lv_obj_set_y( ui_DownloadData, 13 );
lv_obj_set_align( ui_DownloadData, LV_ALIGN_CENTER );
lv_label_set_text(ui_DownloadData,"Download Data");
lv_obj_set_style_text_color(ui_DownloadData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DownloadData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DownloadData, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DownloadData, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back = lv_label_create(ui_SettingDateTime);
lv_obj_set_width( ui_Back, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back, -7 );
lv_obj_set_y( ui_Back, 48 );
lv_obj_set_align( ui_Back, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back,"Back");
lv_obj_set_style_text_color(ui_Back, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
