// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsTempDeviationEnter_screen_init(void)
{
ui_ServiceAlarmsTempDeviationEnter = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsTempDeviationEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsTempDeviationEnter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsTempDeviationEnter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempDeviation1 = lv_label_create(ui_ServiceAlarmsTempDeviationEnter);
lv_obj_set_width( ui_TempDeviation1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempDeviation1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempDeviation1, -6 );
lv_obj_set_y( ui_TempDeviation1, -71 );
lv_obj_set_align( ui_TempDeviation1, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempDeviation1,"Temp Deviation");
lv_obj_set_style_text_color(ui_TempDeviation1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempDeviation1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TempDeviation1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempDeviation1, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue10 = lv_label_create(ui_ServiceAlarmsTempDeviationEnter);
lv_obj_set_width( ui_TemperatureValue10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue10, -7 );
lv_obj_set_y( ui_TemperatureValue10, 0 );
lv_obj_set_align( ui_TemperatureValue10, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue10,"4°C");
lv_obj_set_style_text_color(ui_TemperatureValue10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue10, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue11 = lv_label_create(ui_ServiceAlarmsTempDeviationEnter);
lv_obj_set_width( ui_TemperatureValue11, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue11, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue11, -3 );
lv_obj_set_y( ui_TemperatureValue11, 37 );
lv_obj_set_align( ui_TemperatureValue11, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue11,"3°C");
lv_obj_set_style_text_color(ui_TemperatureValue11, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue11, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue11, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue11, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue12 = lv_label_create(ui_ServiceAlarmsTempDeviationEnter);
lv_obj_set_width( ui_TemperatureValue12, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue12, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue12, -3 );
lv_obj_set_y( ui_TemperatureValue12, 73 );
lv_obj_set_align( ui_TemperatureValue12, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue12,"2°C");
lv_obj_set_style_text_color(ui_TemperatureValue12, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue12, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue12, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue12, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
