// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingDateTimeMinute_screen_init(void)
{
ui_SettingDateTimeMinute = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingDateTimeMinute, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingDateTimeMinute, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingDateTimeMinute, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetYear4 = lv_label_create(ui_SettingDateTimeMinute);
lv_obj_set_width( ui_SetYear4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetYear4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetYear4, 2 );
lv_obj_set_y( ui_SetYear4, -85 );
lv_obj_set_align( ui_SetYear4, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetYear4,"Set Year: 2023");
lv_obj_set_style_text_color(ui_SetYear4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetYear4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetYear4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetYear4, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetMonth4 = lv_label_create(ui_SettingDateTimeMinute);
lv_obj_set_width( ui_SetMonth4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetMonth4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetMonth4, 0 );
lv_obj_set_y( ui_SetMonth4, -54 );
lv_obj_set_align( ui_SetMonth4, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetMonth4,"Set Month: 06");
lv_obj_set_style_text_color(ui_SetMonth4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetMonth4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetMonth4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetMonth4, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetDay4 = lv_label_create(ui_SettingDateTimeMinute);
lv_obj_set_width( ui_SetDay4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetDay4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetDay4, -1 );
lv_obj_set_y( ui_SetDay4, -24 );
lv_obj_set_align( ui_SetDay4, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetDay4,"Set Day: 06");
lv_obj_set_style_text_color(ui_SetDay4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetDay4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetDay4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetDay4, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back9 = lv_label_create(ui_SettingDateTimeMinute);
lv_obj_set_width( ui_Back9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back9, -8 );
lv_obj_set_y( ui_Back9, 84 );
lv_obj_set_align( ui_Back9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back9,"Back");
lv_obj_set_style_text_color(ui_Back9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back9, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetHour4 = lv_label_create(ui_SettingDateTimeMinute);
lv_obj_set_width( ui_SetHour4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetHour4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetHour4, -4 );
lv_obj_set_y( ui_SetHour4, 7 );
lv_obj_set_align( ui_SetHour4, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetHour4,"Set Hour: 06");
lv_obj_set_style_text_color(ui_SetHour4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetHour4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetHour4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetHour4, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetMinute4 = lv_label_create(ui_SettingDateTimeMinute);
lv_obj_set_width( ui_SetMinute4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetMinute4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetMinute4, -3 );
lv_obj_set_y( ui_SetMinute4, 46 );
lv_obj_set_align( ui_SetMinute4, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetMinute4,"Set Minute: 06");
lv_obj_set_style_text_color(ui_SetMinute4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetMinute4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetMinute4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetMinute4, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

}
