// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingData_screen_init(void)
{
ui_SettingData = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingData, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingData, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SettingsDownloadData = lv_label_create(ui_SettingData);
lv_obj_set_width( ui_SettingsDownloadData, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SettingsDownloadData, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SettingsDownloadData, 0 );
lv_obj_set_y( ui_SettingsDownloadData, -96 );
lv_obj_set_align( ui_SettingsDownloadData, LV_ALIGN_CENTER );
lv_label_set_text(ui_SettingsDownloadData,"Settings");
lv_obj_set_style_text_color(ui_SettingsDownloadData, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SettingsDownloadData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SettingsDownloadData, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SettingsDownloadData, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_SettingsDownloadData, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingsDownloadData, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DateTime1 = lv_label_create(ui_SettingData);
lv_obj_set_width( ui_DateTime1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DateTime1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DateTime1, -3 );
lv_obj_set_y( ui_DateTime1, -34 );
lv_obj_set_align( ui_DateTime1, LV_ALIGN_CENTER );
lv_label_set_text(ui_DateTime1,"Date/Time");
lv_obj_set_style_text_color(ui_DateTime1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DateTime1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DateTime1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DateTime1, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DataLoging1 = lv_label_create(ui_SettingData);
lv_obj_set_width( ui_DataLoging1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DataLoging1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DataLoging1, -6 );
lv_obj_set_y( ui_DataLoging1, 5 );
lv_obj_set_align( ui_DataLoging1, LV_ALIGN_CENTER );
lv_label_set_text(ui_DataLoging1,"Download Data");
lv_obj_set_style_text_color(ui_DataLoging1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DataLoging1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DataLoging1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DataLoging1, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back1 = lv_label_create(ui_SettingData);
lv_obj_set_width( ui_Back1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back1, -9 );
lv_obj_set_y( ui_Back1, 47 );
lv_obj_set_align( ui_Back1, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back1,"Back");
lv_obj_set_style_text_color(ui_Back1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back1, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
