// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_Main
void ui_Main_screen_init(void);
lv_obj_t *ui_Main;
lv_obj_t *ui_SpeakerSymbol;
lv_obj_t *ui_temper;
lv_obj_t *ui_Freezer5;
lv_obj_t *ui_ac;
lv_obj_t *ui_BatSymbol;


// SCREEN: ui_OperationModeScreenFreezer
void ui_OperationModeScreenFreezer_screen_init(void);
lv_obj_t *ui_OperationModeScreenFreezer;
lv_obj_t *ui_OpeartionMode;
lv_obj_t *ui_Fridge;
lv_obj_t *ui_Freezer;
lv_obj_t *ui_Back2;


// SCREEN: ui_OperationModeScreenFridge
void ui_OperationModeScreenFridge_screen_init(void);
lv_obj_t *ui_OperationModeScreenFridge;
lv_obj_t *ui_OpeartionMode1;
lv_obj_t *ui_Fridge1;
lv_obj_t *ui_Freezer1;
lv_obj_t *ui_Back3;


// SCREEN: ui_OperationModeScreenBack
void ui_OperationModeScreenBack_screen_init(void);
lv_obj_t *ui_OperationModeScreenBack;
lv_obj_t *ui_OpeartionMode2;
lv_obj_t *ui_Fridge2;
lv_obj_t *ui_Freezer2;
lv_obj_t *ui_Back4;


// SCREEN: ui_SettingDate
void ui_SettingDate_screen_init(void);
lv_obj_t *ui_SettingDate;
lv_obj_t *ui_SettingsDownloadData;
lv_obj_t *ui_DateTime1;
lv_obj_t *ui_DataLoging1;
lv_obj_t *ui_Back1;


// SCREEN: ui_SettingDateTime
void ui_SettingDateTime_screen_init(void);
lv_obj_t *ui_SettingDateTime;
lv_obj_t *ui_Settings;
lv_obj_t *ui_DateTime;
lv_obj_t *ui_DownloadData;
lv_obj_t *ui_Back;


// SCREEN: ui_SettingDateTimeYear
void ui_SettingDateTimeYear_screen_init(void);
lv_obj_t *ui_SettingDateTimeYear;
lv_obj_t *ui_SetYear;
lv_obj_t *ui_SetMonth;
lv_obj_t *ui_SetDay;
lv_obj_t *ui_Back5;
lv_obj_t *ui_SetHour;
lv_obj_t *ui_SetMinute;


// SCREEN: ui_SettingDateTimeMonth
void ui_SettingDateTimeMonth_screen_init(void);
lv_obj_t *ui_SettingDateTimeMonth;
lv_obj_t *ui_SetYear1;
lv_obj_t *ui_SetMonth1;
lv_obj_t *ui_SetDay1;
lv_obj_t *ui_Back6;
lv_obj_t *ui_SetHour1;
lv_obj_t *ui_SetMinute1;


// SCREEN: ui_SettingDateTimeDay
void ui_SettingDateTimeDay_screen_init(void);
lv_obj_t *ui_SettingDateTimeDay;
lv_obj_t *ui_SetYear2;
lv_obj_t *ui_SetMonth2;
lv_obj_t *ui_SetDay2;
lv_obj_t *ui_Back7;
lv_obj_t *ui_SetHour2;
lv_obj_t *ui_SetMinute2;


// SCREEN: ui_SettingDateTimeHour
void ui_SettingDateTimeHour_screen_init(void);
lv_obj_t *ui_SettingDateTimeHour;
lv_obj_t *ui_SetYear3;
lv_obj_t *ui_SetMonth3;
lv_obj_t *ui_SetDay3;
lv_obj_t *ui_Back8;
lv_obj_t *ui_SetHour3;
lv_obj_t *ui_SetMinute3;


// SCREEN: ui_SettingDateTimeMinute
void ui_SettingDateTimeMinute_screen_init(void);
lv_obj_t *ui_SettingDateTimeMinute;
lv_obj_t *ui_SetYear4;
lv_obj_t *ui_SetMonth4;
lv_obj_t *ui_SetDay4;
lv_obj_t *ui_Back9;
lv_obj_t *ui_SetHour4;
lv_obj_t *ui_SetMinute4;


// SCREEN: ui_ServiceTemperature
void ui_ServiceTemperature_screen_init(void);
lv_obj_t *ui_ServiceTemperature;
lv_obj_t *ui_Service;
lv_obj_t *ui_Temperature;
lv_obj_t *ui_Alarms;
lv_obj_t *ui_Back10;
lv_obj_t *ui_DataLogging;
lv_obj_t *ui_Calibrartion;


// SCREEN: ui_ServiceTemperatureFreezer
void ui_ServiceTemperatureFreezer_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFreezer;
lv_obj_t *ui_Temperature1;
lv_obj_t *ui_Fridge3;
lv_obj_t *ui_Freezer3;
lv_obj_t *ui_Back11;


// SCREEN: ui_ServiceTemperatureFridge
void ui_ServiceTemperatureFridge_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFridge;
lv_obj_t *ui_Temperature2;
lv_obj_t *ui_Fridge4;
lv_obj_t *ui_Freezer4;
lv_obj_t *ui_Back12;


// SCREEN: ui_ServiceTemperatureFridgeSetpoint
void ui_ServiceTemperatureFridgeSetpoint_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFridgeSetpoint;
lv_obj_t *ui_FridgeManu;
lv_obj_t *ui_SetPoint;
lv_obj_t *ui_TemperatureValue;
lv_obj_t *ui_Back13;


// SCREEN: ui_ServiceTemperatureFridgeSetTem
void ui_ServiceTemperatureFridgeSetTem_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFridgeSetTem;
lv_obj_t *ui_FridgeManu1;
lv_obj_t *ui_SetPoint1;
lv_obj_t *ui_TemperatureValue1;
lv_obj_t *ui_TemperatureValue2;
lv_obj_t *ui_TemperatureValue3;


// SCREEN: ui_ServiceTemperatureFridgeBack
void ui_ServiceTemperatureFridgeBack_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFridgeBack;
lv_obj_t *ui_FridgeManu2;
lv_obj_t *ui_SetPoint2;
lv_obj_t *ui_TemperatureValue4;
lv_obj_t *ui_Back14;


// SCREEN: ui_ServiceTemperatureFreezeSetpoint
void ui_ServiceTemperatureFreezeSetpoint_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFreezeSetpoint;
lv_obj_t *ui_FreezerManu;
lv_obj_t *ui_SetPoint3;
lv_obj_t *ui_TemperatureValue5;
lv_obj_t *ui_Back15;


// SCREEN: ui_ServiceTemperatureFreezerSetTem
void ui_ServiceTemperatureFreezerSetTem_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFreezerSetTem;
lv_obj_t *ui_FreezerManu1;
lv_obj_t *ui_SetPoint4;
lv_obj_t *ui_TemperatureValue6;
lv_obj_t *ui_TemperatureValue7;
lv_obj_t *ui_TemperatureValue8;


// SCREEN: ui_ServiceTemperatureFeezerBack
void ui_ServiceTemperatureFeezerBack_screen_init(void);
lv_obj_t *ui_ServiceTemperatureFeezerBack;
lv_obj_t *ui_FreezerManu3;
lv_obj_t *ui_SetPoint5;
lv_obj_t *ui_TemperatureValue9;
lv_obj_t *ui_Back16;


// SCREEN: ui_ServiceAlarms
void ui_ServiceAlarms_screen_init(void);
lv_obj_t *ui_ServiceAlarms;
lv_obj_t *ui_Service1;
lv_obj_t *ui_Temperature3;
lv_obj_t *ui_Alarms1;
lv_obj_t *ui_Back17;
lv_obj_t *ui_DataLogging1;
lv_obj_t *ui_Calibrartion1;


// SCREEN: ui_ServiceAlarmsTemp
void ui_ServiceAlarmsTemp_screen_init(void);
lv_obj_t *ui_ServiceAlarmsTemp;
lv_obj_t *ui_Alarms3;
lv_obj_t *ui_Temperature4;
lv_obj_t *ui_Battery;
lv_obj_t *ui_Lid;
lv_obj_t *ui_Back18;
lv_obj_t *ui_MuteAlarms;


// SCREEN: ui_ServiceAlarmsTempDeviation
void ui_ServiceAlarmsTempDeviation_screen_init(void);
lv_obj_t *ui_ServiceAlarmsTempDeviation;
lv_obj_t *ui_TempDeviation;
lv_obj_t *ui_AlarmDelay;
lv_obj_t *ui_Back19;


// SCREEN: ui_ServiceAlarmsTempDeviationEnter
void ui_ServiceAlarmsTempDeviationEnter_screen_init(void);
lv_obj_t *ui_ServiceAlarmsTempDeviationEnter;
lv_obj_t *ui_TempDeviation1;
lv_obj_t *ui_TemperatureValue10;
lv_obj_t *ui_TemperatureValue11;
lv_obj_t *ui_TemperatureValue12;


// SCREEN: ui_WarningScreen
void ui_WarningScreen_screen_init(void);
lv_obj_t *ui_WarningScreen;
lv_obj_t *ui_Fridge5;
lv_obj_t *ui_WarningText;
lv_obj_t *ui_Label1;


// SCREEN: ui_ServiceAlarmsTempAlarmDelay
void ui_ServiceAlarmsTempAlarmDelay_screen_init(void);
lv_obj_t *ui_ServiceAlarmsTempAlarmDelay;
lv_obj_t *ui_TempDeviation2;
lv_obj_t *ui_AlarmDelay1;
lv_obj_t *ui_Back20;


// SCREEN: ui_ServiceAlarmsTempDelaySet
void ui_ServiceAlarmsTempDelaySet_screen_init(void);
lv_obj_t *ui_ServiceAlarmsTempDelaySet;
lv_obj_t *ui_AlarmDelay2;
lv_obj_t *ui_DelayTime1;
lv_obj_t *ui_DelayTime2;
lv_obj_t *ui_DelayTime3;


// SCREEN: ui_ServiceAlarmsBatteryAlarm
void ui_ServiceAlarmsBatteryAlarm_screen_init(void);
lv_obj_t *ui_ServiceAlarmsBatteryAlarm;
lv_obj_t *ui_Alarms2;
lv_obj_t *ui_Temperature5;
lv_obj_t *ui_Battery1;
lv_obj_t *ui_Lid1;
lv_obj_t *ui_Back21;
lv_obj_t *ui_MuteAlarms1;


// SCREEN: ui_ServiceAlarmsBatteryAlarmEnter
void ui_ServiceAlarmsBatteryAlarmEnter_screen_init(void);
lv_obj_t *ui_ServiceAlarmsBatteryAlarmEnter;
lv_obj_t *ui_BatteryAlarm;
lv_obj_t *ui_Battery2;
lv_obj_t *ui_Back22;


// SCREEN: ui_ServiceAlarmsBatteryAlarmBack
void ui_ServiceAlarmsBatteryAlarmBack_screen_init(void);
lv_obj_t *ui_ServiceAlarmsBatteryAlarmBack;
lv_obj_t *ui_BatteryAlarm2;
lv_obj_t *ui_Battery5;
lv_obj_t *ui_Back25;


// SCREEN: ui_ServiceAlarmsBatteryAlarmSet
void ui_ServiceAlarmsBatteryAlarmSet_screen_init(void);
lv_obj_t *ui_ServiceAlarmsBatteryAlarmSet;
lv_obj_t *ui_BatteryAlarm1;
lv_obj_t *ui_BatValue1;
lv_obj_t *ui_BatValue2;
lv_obj_t *ui_BatValue3;


// SCREEN: ui_ServiceAlarmsLid
void ui_ServiceAlarmsLid_screen_init(void);
lv_obj_t *ui_ServiceAlarmsLid;
lv_obj_t *ui_Alarms4;
lv_obj_t *ui_Temperature6;
lv_obj_t *ui_Battery3;
lv_obj_t *ui_Lid2;
lv_obj_t *ui_Back23;
lv_obj_t *ui_MuteAlarms2;


// SCREEN: ui_ServiceAlarmsLidEnter
void ui_ServiceAlarmsLidEnter_screen_init(void);
lv_obj_t *ui_ServiceAlarmsLidEnter;
lv_obj_t *ui_LidAlarm;
lv_obj_t *ui_TimeValue6;
lv_obj_t *ui_Back24;


// SCREEN: ui_ServiceAlarmsLidSet
void ui_ServiceAlarmsLidSet_screen_init(void);
lv_obj_t *ui_ServiceAlarmsLidSet;
lv_obj_t *ui_BatteryAlarm3;
lv_obj_t *ui_TimeValue3;
lv_obj_t *ui_TimeValue4;
lv_obj_t *ui_TimeValue5;


// SCREEN: ui_ServiceAlarmsLidBack
void ui_ServiceAlarmsLidBack_screen_init(void);
lv_obj_t *ui_ServiceAlarmsLidBack;
lv_obj_t *ui_LidAlarm1;
lv_obj_t *ui_TimeValue2;
lv_obj_t *ui_Back26;


// SCREEN: ui_ServiceAlarmsMuteAlarm
void ui_ServiceAlarmsMuteAlarm_screen_init(void);
lv_obj_t *ui_ServiceAlarmsMuteAlarm;
lv_obj_t *ui_Alarms5;
lv_obj_t *ui_Temperature7;
lv_obj_t *ui_Battery7;
lv_obj_t *ui_Lid3;
lv_obj_t *ui_Back27;
lv_obj_t *ui_MuteAlarms3;


// SCREEN: ui_ServiceAlarmsMuteAlarmEnter
void ui_ServiceAlarmsMuteAlarmEnter_screen_init(void);
lv_obj_t *ui_ServiceAlarmsMuteAlarmEnter;
lv_obj_t *ui_MuteDuration;
lv_obj_t *ui_TimeValue;
lv_obj_t *ui_Back28;


// SCREEN: ui_ServiceAlarmsMuteAlarmSet
void ui_ServiceAlarmsMuteAlarmSet_screen_init(void);
lv_obj_t *ui_ServiceAlarmsMuteAlarmSet;
lv_obj_t *ui_MuteDuration1;
lv_obj_t *ui_TimeValue1;
lv_obj_t *ui_TimeValue7;
lv_obj_t *ui_TimeValue8;


// SCREEN: ui_ServiceAlarmsMuteAlarmBack
void ui_ServiceAlarmsMuteAlarmBack_screen_init(void);
lv_obj_t *ui_ServiceAlarmsMuteAlarmBack;
lv_obj_t *ui_MuteDuration2;
lv_obj_t *ui_TimeValue9;
lv_obj_t *ui_Back29;


// SCREEN: ui_ServiceAlarmsBack
void ui_ServiceAlarmsBack_screen_init(void);
lv_obj_t *ui_ServiceAlarmsBack;
lv_obj_t *ui_Alarms6;
lv_obj_t *ui_Temperature8;
lv_obj_t *ui_Battery4;
lv_obj_t *ui_Lid4;
lv_obj_t *ui_Back30;
lv_obj_t *ui_MuteAlarms4;


// SCREEN: ui_ServiceDataLogging
void ui_ServiceDataLogging_screen_init(void);
lv_obj_t *ui_ServiceDataLogging;
lv_obj_t *ui_Service2;
lv_obj_t *ui_Temperature9;
lv_obj_t *ui_Alarms7;
lv_obj_t *ui_Back31;
lv_obj_t *ui_DataLogging2;
lv_obj_t *ui_Calibrartion2;


// SCREEN: ui_ServiceDataLoggingEnter
void ui_ServiceDataLoggingEnter_screen_init(void);
lv_obj_t *ui_ServiceDataLoggingEnter;
lv_obj_t *ui_DataLogging3;
lv_obj_t *ui_LoggingInterval;
lv_obj_t *ui_Back32;


// SCREEN: ui_ServiceDataLoggingIntervalSet
void ui_ServiceDataLoggingIntervalSet_screen_init(void);
lv_obj_t *ui_ServiceDataLoggingIntervalSet;
lv_obj_t *ui_LoggingInterval1;
lv_obj_t *ui_DelayTime4;
lv_obj_t *ui_DelayTime5;
lv_obj_t *ui_DelayTime6;


// SCREEN: ui_ServiceDataLoggingBack
void ui_ServiceDataLoggingBack_screen_init(void);
lv_obj_t *ui_ServiceDataLoggingBack;
lv_obj_t *ui_DataLogging4;
lv_obj_t *ui_LoggingInterval2;
lv_obj_t *ui_Back33;


// SCREEN: ui_ServiceCalibration
void ui_ServiceCalibration_screen_init(void);
lv_obj_t *ui_ServiceCalibration;
lv_obj_t *ui_Service3;
lv_obj_t *ui_Temperature10;
lv_obj_t *ui_Alarms8;
lv_obj_t *ui_Back34;
lv_obj_t *ui_DataLogging5;
lv_obj_t *ui_Calibrartion3;


// SCREEN: ui_ServiceCalibrationEnter
void ui_ServiceCalibrationEnter_screen_init(void);
lv_obj_t *ui_ServiceCalibrationEnter;
lv_obj_t *ui_Calibrartion4;
lv_obj_t *ui_TemperOffset;
lv_obj_t *ui_Back35;


// SCREEN: ui_ServiceCalibrationEnterSet
void ui_ServiceCalibrationEnterSet_screen_init(void);
lv_obj_t *ui_ServiceCalibrationEnterSet;
lv_obj_t *ui_TemperOffset1;
lv_obj_t *ui_TemperatureValue13;
lv_obj_t *ui_TemperatureValue14;
lv_obj_t *ui_TemperatureValue15;


// SCREEN: ui_ServiceCalibrationBack
void ui_ServiceCalibrationBack_screen_init(void);
lv_obj_t *ui_ServiceCalibrationBack;
lv_obj_t *ui_Calibrartion5;
lv_obj_t *ui_TemperOffset3;
lv_obj_t *ui_Back36;
lv_obj_t *ui____initial_actions0;

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 16
    #error "LV_COLOR_DEPTH should be 16bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////

///////////////////// SCREENS ////////////////////

void ui_init( void )
{
lv_disp_t *dispp = lv_disp_get_default();
lv_theme_t *theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED), false, LV_FONT_DEFAULT);
lv_disp_set_theme(dispp, theme);
ui_Main_screen_init();
//ui_OperationModeScreenFreezer_screen_init();
//ui_OperationModeScreenFridge_screen_init();
//ui_OperationModeScreenBack_screen_init();
//ui_SettingDate_screen_init();
//ui_SettingDateTime_screen_init();
//ui_SettingDateTimeYear_screen_init();
//ui_SettingDateTimeMonth_screen_init();
//ui_SettingDateTimeDay_screen_init();
//ui_SettingDateTimeHour_screen_init();
//ui_SettingDateTimeMinute_screen_init();
//ui_ServiceTemperature_screen_init();
//ui_ServiceTemperatureFreezer_screen_init();
//ui_ServiceTemperatureFridge_screen_init();
//ui_ServiceTemperatureFridgeSetpoint_screen_init();
//ui_ServiceTemperatureFridgeSetTem_screen_init();
//ui_ServiceTemperatureFridgeBack_screen_init();
//ui_ServiceTemperatureFreezeSetpoint_screen_init();
//ui_ServiceTemperatureFreezerSetTem_screen_init();
//ui_ServiceTemperatureFeezerBack_screen_init();
//ui_ServiceAlarms_screen_init();
//ui_ServiceAlarmsTemp_screen_init();
//ui_ServiceAlarmsTempDeviation_screen_init();
//ui_ServiceAlarmsTempDeviationEnter_screen_init();
//ui_WarningScreen_screen_init();
//ui_ServiceAlarmsTempAlarmDelay_screen_init();
//ui_ServiceAlarmsTempDelaySet_screen_init();
//ui_ServiceAlarmsBatteryAlarm_screen_init();
//ui_ServiceAlarmsBatteryAlarmEnter_screen_init();
//ui_ServiceAlarmsBatteryAlarmBack_screen_init();
//ui_ServiceAlarmsBatteryAlarmSet_screen_init();
//ui_ServiceAlarmsLid_screen_init();
//ui_ServiceAlarmsLidEnter_screen_init();
//ui_ServiceAlarmsLidSet_screen_init();
//ui_ServiceAlarmsLidBack_screen_init();
//ui_ServiceAlarmsMuteAlarm_screen_init();
//ui_ServiceAlarmsMuteAlarmEnter_screen_init();
//ui_ServiceAlarmsMuteAlarmSet_screen_init();
//ui_ServiceAlarmsMuteAlarmBack_screen_init();
//ui_ServiceAlarmsBack_screen_init();
//ui_ServiceDataLogging_screen_init();
//ui_ServiceDataLoggingEnter_screen_init();
//ui_ServiceDataLoggingIntervalSet_screen_init();
//ui_ServiceDataLoggingBack_screen_init();
//ui_ServiceCalibration_screen_init();
//ui_ServiceCalibrationEnter_screen_init();
//ui_ServiceCalibrationEnterSet_screen_init();
//ui_ServiceCalibrationBack_screen_init();
ui____initial_actions0 = lv_obj_create(NULL);
lv_disp_load_scr( ui_Main);
}
