// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
// SCREEN: ui_Main
void ui_Main_screen_init(void);
extern lv_obj_t *ui_Main;
extern lv_obj_t *ui_SpeakerSymbol;
extern lv_obj_t *ui_temper;
extern lv_obj_t *ui_Freezer5;
extern lv_obj_t *ui_ac;
extern lv_obj_t *ui_BatSymbol;
// SCREEN: ui_OperationModeScreenFreezer
void ui_OperationModeScreenFreezer_screen_init(void);
extern lv_obj_t *ui_OperationModeScreenFreezer;
extern lv_obj_t *ui_OpeartionMode;
extern lv_obj_t *ui_Fridge;
extern lv_obj_t *ui_Freezer;
extern lv_obj_t *ui_Back2;
// SCREEN: ui_OperationModeScreenFridge
void ui_OperationModeScreenFridge_screen_init(void);
extern lv_obj_t *ui_OperationModeScreenFridge;
extern lv_obj_t *ui_OpeartionMode1;
extern lv_obj_t *ui_Fridge1;
extern lv_obj_t *ui_Freezer1;
extern lv_obj_t *ui_Back3;
// SCREEN: ui_OperationModeScreenBack
void ui_OperationModeScreenBack_screen_init(void);
extern lv_obj_t *ui_OperationModeScreenBack;
extern lv_obj_t *ui_OpeartionMode2;
extern lv_obj_t *ui_Fridge2;
extern lv_obj_t *ui_Freezer2;
extern lv_obj_t *ui_Back4;
// SCREEN: ui_SettingDate
void ui_SettingDate_screen_init(void);
extern lv_obj_t *ui_SettingDate;
extern lv_obj_t *ui_SettingsDownloadData;
extern lv_obj_t *ui_DateTime1;
extern lv_obj_t *ui_DataLoging1;
extern lv_obj_t *ui_Back1;
// SCREEN: ui_SettingDateTime
void ui_SettingDateTime_screen_init(void);
extern lv_obj_t *ui_SettingDateTime;
extern lv_obj_t *ui_Settings;
extern lv_obj_t *ui_DateTime;
extern lv_obj_t *ui_DownloadData;
extern lv_obj_t *ui_Back;
// SCREEN: ui_SettingDateTimeYear
void ui_SettingDateTimeYear_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeYear;
extern lv_obj_t *ui_SetYear;
extern lv_obj_t *ui_SetMonth;
extern lv_obj_t *ui_SetDay;
extern lv_obj_t *ui_Back5;
extern lv_obj_t *ui_SetHour;
extern lv_obj_t *ui_SetMinute;
// SCREEN: ui_SettingDateTimeMonth
void ui_SettingDateTimeMonth_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeMonth;
extern lv_obj_t *ui_SetYear1;
extern lv_obj_t *ui_SetMonth1;
extern lv_obj_t *ui_SetDay1;
extern lv_obj_t *ui_Back6;
extern lv_obj_t *ui_SetHour1;
extern lv_obj_t *ui_SetMinute1;
// SCREEN: ui_SettingDateTimeDay
void ui_SettingDateTimeDay_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeDay;
extern lv_obj_t *ui_SetYear2;
extern lv_obj_t *ui_SetMonth2;
extern lv_obj_t *ui_SetDay2;
extern lv_obj_t *ui_Back7;
extern lv_obj_t *ui_SetHour2;
extern lv_obj_t *ui_SetMinute2;
// SCREEN: ui_SettingDateTimeHour
void ui_SettingDateTimeHour_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeHour;
extern lv_obj_t *ui_SetYear3;
extern lv_obj_t *ui_SetMonth3;
extern lv_obj_t *ui_SetDay3;
extern lv_obj_t *ui_Back8;
extern lv_obj_t *ui_SetHour3;
extern lv_obj_t *ui_SetMinute3;
// SCREEN: ui_SettingDateTimeMinute
void ui_SettingDateTimeMinute_screen_init(void);
extern lv_obj_t *ui_SettingDateTimeMinute;
extern lv_obj_t *ui_SetYear4;
extern lv_obj_t *ui_SetMonth4;
extern lv_obj_t *ui_SetDay4;
extern lv_obj_t *ui_Back9;
extern lv_obj_t *ui_SetHour4;
extern lv_obj_t *ui_SetMinute4;
// SCREEN: ui_ServiceTemperature
void ui_ServiceTemperature_screen_init(void);
extern lv_obj_t *ui_ServiceTemperature;
extern lv_obj_t *ui_Service;
extern lv_obj_t *ui_Temperature;
extern lv_obj_t *ui_Alarms;
extern lv_obj_t *ui_Back10;
extern lv_obj_t *ui_DataLogging;
extern lv_obj_t *ui_Calibrartion;
// SCREEN: ui_ServiceTemperatureFreezer
void ui_ServiceTemperatureFreezer_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFreezer;
extern lv_obj_t *ui_Temperature1;
extern lv_obj_t *ui_Fridge3;
extern lv_obj_t *ui_Freezer3;
extern lv_obj_t *ui_Back11;
// SCREEN: ui_ServiceTemperatureFridge
void ui_ServiceTemperatureFridge_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFridge;
extern lv_obj_t *ui_Temperature2;
extern lv_obj_t *ui_Fridge4;
extern lv_obj_t *ui_Freezer4;
extern lv_obj_t *ui_Back12;
// SCREEN: ui_ServiceTemperatureFridgeSetpoint
void ui_ServiceTemperatureFridgeSetpoint_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFridgeSetpoint;
extern lv_obj_t *ui_FridgeManu;
extern lv_obj_t *ui_SetPoint;
extern lv_obj_t *ui_TemperatureValue;
extern lv_obj_t *ui_Back13;
// SCREEN: ui_ServiceTemperatureFridgeSetTem
void ui_ServiceTemperatureFridgeSetTem_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFridgeSetTem;
extern lv_obj_t *ui_FridgeManu1;
extern lv_obj_t *ui_SetPoint1;
extern lv_obj_t *ui_TemperatureValue1;
extern lv_obj_t *ui_TemperatureValue2;
extern lv_obj_t *ui_TemperatureValue3;
// SCREEN: ui_ServiceTemperatureFridgeBack
void ui_ServiceTemperatureFridgeBack_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFridgeBack;
extern lv_obj_t *ui_FridgeManu2;
extern lv_obj_t *ui_SetPoint2;
extern lv_obj_t *ui_TemperatureValue4;
extern lv_obj_t *ui_Back14;
// SCREEN: ui_ServiceTemperatureFreezeSetpoint
void ui_ServiceTemperatureFreezeSetpoint_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFreezeSetpoint;
extern lv_obj_t *ui_FreezerManu;
extern lv_obj_t *ui_SetPoint3;
extern lv_obj_t *ui_TemperatureValue5;
extern lv_obj_t *ui_Back15;
// SCREEN: ui_ServiceTemperatureFreezerSetTem
void ui_ServiceTemperatureFreezerSetTem_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFreezerSetTem;
extern lv_obj_t *ui_FreezerManu1;
extern lv_obj_t *ui_SetPoint4;
extern lv_obj_t *ui_TemperatureValue6;
extern lv_obj_t *ui_TemperatureValue7;
extern lv_obj_t *ui_TemperatureValue8;
// SCREEN: ui_ServiceTemperatureFeezerBack
void ui_ServiceTemperatureFeezerBack_screen_init(void);
extern lv_obj_t *ui_ServiceTemperatureFeezerBack;
extern lv_obj_t *ui_FreezerManu3;
extern lv_obj_t *ui_SetPoint5;
extern lv_obj_t *ui_TemperatureValue9;
extern lv_obj_t *ui_Back16;
// SCREEN: ui_ServiceAlarms
void ui_ServiceAlarms_screen_init(void);
extern lv_obj_t *ui_ServiceAlarms;
extern lv_obj_t *ui_Service1;
extern lv_obj_t *ui_Temperature3;
extern lv_obj_t *ui_Alarms1;
extern lv_obj_t *ui_Back17;
extern lv_obj_t *ui_DataLogging1;
extern lv_obj_t *ui_Calibrartion1;
// SCREEN: ui_ServiceAlarmsTemp
void ui_ServiceAlarmsTemp_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsTemp;
extern lv_obj_t *ui_Alarms3;
extern lv_obj_t *ui_Temperature4;
extern lv_obj_t *ui_Battery;
extern lv_obj_t *ui_Lid;
extern lv_obj_t *ui_Back18;
extern lv_obj_t *ui_MuteAlarms;
// SCREEN: ui_ServiceAlarmsTempDeviation
void ui_ServiceAlarmsTempDeviation_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsTempDeviation;
extern lv_obj_t *ui_TempDeviation;
extern lv_obj_t *ui_AlarmDelay;
extern lv_obj_t *ui_Back19;
// SCREEN: ui_ServiceAlarmsTempDeviationEnter
void ui_ServiceAlarmsTempDeviationEnter_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsTempDeviationEnter;
extern lv_obj_t *ui_TempDeviation1;
extern lv_obj_t *ui_TemperatureValue10;
extern lv_obj_t *ui_TemperatureValue11;
extern lv_obj_t *ui_TemperatureValue12;
// SCREEN: ui_WarningScreen
void ui_WarningScreen_screen_init(void);
extern lv_obj_t *ui_WarningScreen;
extern lv_obj_t *ui_Fridge5;
extern lv_obj_t *ui_WarningText;
extern lv_obj_t *ui_Label1;
// SCREEN: ui_ServiceAlarmsTempAlarmDelay
void ui_ServiceAlarmsTempAlarmDelay_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsTempAlarmDelay;
extern lv_obj_t *ui_TempDeviation2;
extern lv_obj_t *ui_AlarmDelay1;
extern lv_obj_t *ui_Back20;
// SCREEN: ui_ServiceAlarmsTempDelaySet
void ui_ServiceAlarmsTempDelaySet_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsTempDelaySet;
extern lv_obj_t *ui_AlarmDelay2;
extern lv_obj_t *ui_DelayTime1;
extern lv_obj_t *ui_DelayTime2;
extern lv_obj_t *ui_DelayTime3;
// SCREEN: ui_ServiceAlarmsBatteryAlarm
void ui_ServiceAlarmsBatteryAlarm_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsBatteryAlarm;
extern lv_obj_t *ui_Alarms2;
extern lv_obj_t *ui_Temperature5;
extern lv_obj_t *ui_Battery1;
extern lv_obj_t *ui_Lid1;
extern lv_obj_t *ui_Back21;
extern lv_obj_t *ui_MuteAlarms1;
// SCREEN: ui_ServiceAlarmsBatteryAlarmEnter
void ui_ServiceAlarmsBatteryAlarmEnter_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsBatteryAlarmEnter;
extern lv_obj_t *ui_BatteryAlarm;
extern lv_obj_t *ui_Battery2;
extern lv_obj_t *ui_Back22;
// SCREEN: ui_ServiceAlarmsBatteryAlarmBack
void ui_ServiceAlarmsBatteryAlarmBack_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsBatteryAlarmBack;
extern lv_obj_t *ui_BatteryAlarm2;
extern lv_obj_t *ui_Battery5;
extern lv_obj_t *ui_Back25;
// SCREEN: ui_ServiceAlarmsBatteryAlarmSet
void ui_ServiceAlarmsBatteryAlarmSet_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsBatteryAlarmSet;
extern lv_obj_t *ui_BatteryAlarm1;
extern lv_obj_t *ui_BatValue1;
extern lv_obj_t *ui_BatValue2;
extern lv_obj_t *ui_BatValue3;
// SCREEN: ui_ServiceAlarmsLid
void ui_ServiceAlarmsLid_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsLid;
extern lv_obj_t *ui_Alarms4;
extern lv_obj_t *ui_Temperature6;
extern lv_obj_t *ui_Battery3;
extern lv_obj_t *ui_Lid2;
extern lv_obj_t *ui_Back23;
extern lv_obj_t *ui_MuteAlarms2;
// SCREEN: ui_ServiceAlarmsLidEnter
void ui_ServiceAlarmsLidEnter_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsLidEnter;
extern lv_obj_t *ui_LidAlarm;
extern lv_obj_t *ui_TimeValue6;
extern lv_obj_t *ui_Back24;
// SCREEN: ui_ServiceAlarmsLidSet
void ui_ServiceAlarmsLidSet_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsLidSet;
extern lv_obj_t *ui_BatteryAlarm3;
extern lv_obj_t *ui_TimeValue3;
extern lv_obj_t *ui_TimeValue4;
extern lv_obj_t *ui_TimeValue5;
// SCREEN: ui_ServiceAlarmsLidBack
void ui_ServiceAlarmsLidBack_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsLidBack;
extern lv_obj_t *ui_LidAlarm1;
extern lv_obj_t *ui_TimeValue2;
extern lv_obj_t *ui_Back26;
// SCREEN: ui_ServiceAlarmsMuteAlarm
void ui_ServiceAlarmsMuteAlarm_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsMuteAlarm;
extern lv_obj_t *ui_Alarms5;
extern lv_obj_t *ui_Temperature7;
extern lv_obj_t *ui_Battery7;
extern lv_obj_t *ui_Lid3;
extern lv_obj_t *ui_Back27;
extern lv_obj_t *ui_MuteAlarms3;
// SCREEN: ui_ServiceAlarmsMuteAlarmEnter
void ui_ServiceAlarmsMuteAlarmEnter_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsMuteAlarmEnter;
extern lv_obj_t *ui_MuteDuration;
extern lv_obj_t *ui_TimeValue;
extern lv_obj_t *ui_Back28;
// SCREEN: ui_ServiceAlarmsMuteAlarmSet
void ui_ServiceAlarmsMuteAlarmSet_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsMuteAlarmSet;
extern lv_obj_t *ui_MuteDuration1;
extern lv_obj_t *ui_TimeValue1;
extern lv_obj_t *ui_TimeValue7;
extern lv_obj_t *ui_TimeValue8;
// SCREEN: ui_ServiceAlarmsMuteAlarmBack
void ui_ServiceAlarmsMuteAlarmBack_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsMuteAlarmBack;
extern lv_obj_t *ui_MuteDuration2;
extern lv_obj_t *ui_TimeValue9;
extern lv_obj_t *ui_Back29;
// SCREEN: ui_ServiceAlarmsBack
void ui_ServiceAlarmsBack_screen_init(void);
extern lv_obj_t *ui_ServiceAlarmsBack;
extern lv_obj_t *ui_Alarms6;
extern lv_obj_t *ui_Temperature8;
extern lv_obj_t *ui_Battery4;
extern lv_obj_t *ui_Lid4;
extern lv_obj_t *ui_Back30;
extern lv_obj_t *ui_MuteAlarms4;
// SCREEN: ui_ServiceDataLogging
void ui_ServiceDataLogging_screen_init(void);
extern lv_obj_t *ui_ServiceDataLogging;
extern lv_obj_t *ui_Service2;
extern lv_obj_t *ui_Temperature9;
extern lv_obj_t *ui_Alarms7;
extern lv_obj_t *ui_Back31;
extern lv_obj_t *ui_DataLogging2;
extern lv_obj_t *ui_Calibrartion2;
// SCREEN: ui_ServiceDataLoggingEnter
void ui_ServiceDataLoggingEnter_screen_init(void);
extern lv_obj_t *ui_ServiceDataLoggingEnter;
extern lv_obj_t *ui_DataLogging3;
extern lv_obj_t *ui_LoggingInterval;
extern lv_obj_t *ui_Back32;
// SCREEN: ui_ServiceDataLoggingIntervalSet
void ui_ServiceDataLoggingIntervalSet_screen_init(void);
extern lv_obj_t *ui_ServiceDataLoggingIntervalSet;
extern lv_obj_t *ui_LoggingInterval1;
extern lv_obj_t *ui_DelayTime4;
extern lv_obj_t *ui_DelayTime5;
extern lv_obj_t *ui_DelayTime6;
// SCREEN: ui_ServiceDataLoggingBack
void ui_ServiceDataLoggingBack_screen_init(void);
extern lv_obj_t *ui_ServiceDataLoggingBack;
extern lv_obj_t *ui_DataLogging4;
extern lv_obj_t *ui_LoggingInterval2;
extern lv_obj_t *ui_Back33;
// SCREEN: ui_ServiceCalibration
void ui_ServiceCalibration_screen_init(void);
extern lv_obj_t *ui_ServiceCalibration;
extern lv_obj_t *ui_Service3;
extern lv_obj_t *ui_Temperature10;
extern lv_obj_t *ui_Alarms8;
extern lv_obj_t *ui_Back34;
extern lv_obj_t *ui_DataLogging5;
extern lv_obj_t *ui_Calibrartion3;
// SCREEN: ui_ServiceCalibrationEnter
void ui_ServiceCalibrationEnter_screen_init(void);
extern lv_obj_t *ui_ServiceCalibrationEnter;
extern lv_obj_t *ui_Calibrartion4;
extern lv_obj_t *ui_TemperOffset;
extern lv_obj_t *ui_Back35;
// SCREEN: ui_ServiceCalibrationEnterSet
void ui_ServiceCalibrationEnterSet_screen_init(void);
extern lv_obj_t *ui_ServiceCalibrationEnterSet;
extern lv_obj_t *ui_TemperOffset1;
extern lv_obj_t *ui_TemperatureValue13;
extern lv_obj_t *ui_TemperatureValue14;
extern lv_obj_t *ui_TemperatureValue15;
// SCREEN: ui_ServiceCalibrationBack
void ui_ServiceCalibrationBack_screen_init(void);
extern lv_obj_t *ui_ServiceCalibrationBack;
extern lv_obj_t *ui_Calibrartion5;
extern lv_obj_t *ui_TemperOffset3;
extern lv_obj_t *ui_Back36;
extern lv_obj_t *ui____initial_actions0;



LV_FONT_DECLARE( ui_font_verdana244);
LV_FONT_DECLARE( ui_font_verdana364);
LV_FONT_DECLARE( ui_font_verdana404);

void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
