files:
- generatedChecksum: F15D3E1211F70BD0389E770D8822D54E
  logicalPath: config/pic32mk_gp_lib
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: F15D3E1211F70BD0389E770D8822D54E
- generatedChecksum: 3ABE71CC460C8F75B80A2208903ACBF7
  logicalPath: config/pic32mk_gp_lib
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3ABE71CC460C8F75B80A2208903ACBF7
- generatedChecksum: B82DD533A637970200A30A23CD5A84CB
  logicalPath: config/pic32mk_gp_lib
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B82DD533A637970200A30A23CD5A84CB
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: B159AE4EAE8D349A26638E535FAB825B
  logicalPath: config/pic32mk_gp_lib/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: B159AE4EAE8D349A26638E535FAB825B
- generatedChecksum: D9F5B35B179319EFFEC6D6D29E9824F2
  logicalPath: config/pic32mk_gp_lib/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: D9F5B35B179319EFFEC6D6D29E9824F2
- generatedChecksum: 983EBD221A12A5AD7075CECCD822EA0A
  logicalPath: config/pic32mk_gp_lib/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 983EBD221A12A5AD7075CECCD822EA0A
- generatedChecksum: 832BAA1604836C02220A47169C724665
  logicalPath: config/pic32mk_gp_lib/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 832BAA1604836C02220A47169C724665
- generatedChecksum: 84FB5CFB34103ECBD2C2A897844E53B8
  logicalPath: config/pic32mk_gp_lib/peripheral/spi/spi_master
  name: plib_spi5_master.c
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: SOURCE
  userChecksum: 84FB5CFB34103ECBD2C2A897844E53B8
- generatedChecksum: 752F42263FAAA19A2ADFBB262B52AC1C
  logicalPath: config/pic32mk_gp_lib/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 752F42263FAAA19A2ADFBB262B52AC1C
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mk_gp_lib/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: A3041FB559B162295CCBEC3BA0030C43
  logicalPath: config/pic32mk_gp_lib
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4E71DF4B14EAA32CF2A9DB0C326A5AC2
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mk_gp_lib
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 50B3C678282C21181FCCC9B8555CA582
  logicalPath: config/pic32mk_gp_lib
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 50B3C678282C21181FCCC9B8555CA582
- generatedChecksum: AEE67D74C4226BAD4A952A8E4C860C89
  logicalPath: config/pic32mk_gp_lib/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: AEE67D74C4226BAD4A952A8E4C860C89
- generatedChecksum: 5F897AB3CA947017163BB9E458AB73B0
  logicalPath: config/pic32mk_gp_lib/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 5F897AB3CA947017163BB9E458AB73B0
- generatedChecksum: 659C36DDECEB5D45A408CB5469FDCD0A
  logicalPath: config/pic32mk_gp_lib/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 659C36DDECEB5D45A408CB5469FDCD0A
- generatedChecksum: FFEF01F6CAA6A5335B247CDDFCA1A970
  logicalPath: config/pic32mk_gp_lib/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: FFEF01F6CAA6A5335B247CDDFCA1A970
- generatedChecksum: 7FBD6ABF55B2AAEA3DADB317704AE988
  logicalPath: config/pic32mk_gp_lib/peripheral/spi/spi_master
  name: plib_spi5_master.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: 7FBD6ABF55B2AAEA3DADB317704AE988
- generatedChecksum: CFA758C8B7258190473EF7C60C4BA4E9
  logicalPath: config/pic32mk_gp_lib/peripheral/spi/spi_master
  name: plib_spi_master_common.h
  physicalPath: peripheral/spi/spi_master
  security: NON_SECURE
  type: HEADER
  userChecksum: CFA758C8B7258190473EF7C60C4BA4E9
- generatedChecksum: A9CFABEFF2885869E00956555ACB34B1
  logicalPath: config/pic32mk_gp_lib/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: A9CFABEFF2885869E00956555ACB34B1
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/pic32mk_gp_lib/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: F34DBA93CC6DB1AA4CE3C4E95491B979
  logicalPath: config/pic32mk_gp_lib
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: F34DBA93CC6DB1AA4CE3C4E95491B979
- generatedChecksum: F63F6B4411CE1D60A4EF9FE43872F4E2
  logicalPath: config/pic32mk_gp_lib
  name: p32MK1024GPD064.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: F63F6B4411CE1D60A4EF9FE43872F4E2
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_lib;
- append: false
  category: C32
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mk_gp_lib;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-micro-compressed-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
