format_version: v1.0
type: UniqueComponent
attributes: {id: spi5}
children:
- type: Symbols
  children:
  - type: Boolean
    attributes: {id: SPIS_SLAVE_SELECT_ENABLE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi5, value: 'true'}
  - type: Integer
    attributes: {id: SPI_BAUD_RATE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '4000000'}
  - type: Integer
    attributes: {id: SPI_BRG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi5, value: '4'}
  - type: Boolean
    attributes: {id: SPI_INTERRUPT_MODE}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'false'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi5, value: 'true'}
  - type: KeyValueSet
    attributes: {id: SPI_MSTR_MODE_EN}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: readOnly}
        children:
        - {type: Value, value: 'true'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: spi5, value: '0'}
  - type: KeyValueSet
    attributes: {id: SPI_SPICON_MSSEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
- type: ElementPosition
  attributes: {x: '18', y: '261', id: spi5}
