// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_OperationModeScreenFreezer_screen_init(void)
{
ui_OperationModeScreenFreezer = lv_obj_create(NULL);
lv_obj_clear_flag( ui_OperationModeScreenFreezer, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_OperationModeScreenFreezer, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OperationModeScreenFreezer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OpeartionMode = lv_label_create(ui_OperationModeScreenFreezer);
lv_obj_set_width( ui_OpeartionMode, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OpeartionMode, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OpeartionMode, 0 );
lv_obj_set_y( ui_OpeartionMode, -96 );
lv_obj_set_align( ui_OpeartionMode, LV_ALIGN_CENTER );
lv_label_set_text(ui_OpeartionMode,"Operation Mode");
lv_obj_set_style_text_color(ui_OpeartionMode, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OpeartionMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_OpeartionMode, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OpeartionMode, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OpeartionMode, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OpeartionMode, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Fridge = lv_label_create(ui_OperationModeScreenFreezer);
lv_obj_set_width( ui_Fridge, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Fridge, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Fridge, -1 );
lv_obj_set_y( ui_Fridge, -28 );
lv_obj_set_align( ui_Fridge, LV_ALIGN_CENTER );
lv_label_set_text(ui_Fridge,"Fridge");
lv_obj_set_style_text_color(ui_Fridge, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Fridge, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Fridge, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Fridge, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freezer = lv_label_create(ui_OperationModeScreenFreezer);
lv_obj_set_width( ui_Freezer, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Freezer, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Freezer, -7 );
lv_obj_set_y( ui_Freezer, 10 );
lv_obj_set_align( ui_Freezer, LV_ALIGN_CENTER );
lv_label_set_text(ui_Freezer,"Freezer");
lv_obj_set_style_text_color(ui_Freezer, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freezer, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Freezer, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Freezer, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back2 = lv_label_create(ui_OperationModeScreenFreezer);
lv_obj_set_width( ui_Back2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back2, -4 );
lv_obj_set_y( ui_Back2, 51 );
lv_obj_set_align( ui_Back2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back2,"Back");
lv_obj_set_style_text_color(ui_Back2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
