// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_OperationModeScreenBack_screen_init(void)
{
ui_OperationModeScreenBack = lv_obj_create(NULL);
lv_obj_clear_flag( ui_OperationModeScreenBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_OperationModeScreenBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OperationModeScreenBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_OpeartionMode2 = lv_label_create(ui_OperationModeScreenBack);
lv_obj_set_width( ui_OpeartionMode2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_OpeartionMode2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_OpeartionMode2, 0 );
lv_obj_set_y( ui_OpeartionMode2, -96 );
lv_obj_set_align( ui_OpeartionMode2, LV_ALIGN_CENTER );
lv_label_set_text(ui_OpeartionMode2,"Operation Mode");
lv_obj_set_style_text_color(ui_OpeartionMode2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_OpeartionMode2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_OpeartionMode2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_OpeartionMode2, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_OpeartionMode2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_OpeartionMode2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Fridge2 = lv_label_create(ui_OperationModeScreenBack);
lv_obj_set_width( ui_Fridge2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Fridge2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Fridge2, -1 );
lv_obj_set_y( ui_Fridge2, -28 );
lv_obj_set_align( ui_Fridge2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Fridge2,"Fridge");
lv_obj_set_style_text_color(ui_Fridge2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Fridge2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Fridge2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Fridge2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Freezer2 = lv_label_create(ui_OperationModeScreenBack);
lv_obj_set_width( ui_Freezer2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Freezer2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Freezer2, -7 );
lv_obj_set_y( ui_Freezer2, 10 );
lv_obj_set_align( ui_Freezer2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Freezer2,"Freezer");
lv_obj_set_style_text_color(ui_Freezer2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Freezer2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Freezer2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Freezer2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back4 = lv_label_create(ui_OperationModeScreenBack);
lv_obj_set_width( ui_Back4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back4, -4 );
lv_obj_set_y( ui_Back4, 51 );
lv_obj_set_align( ui_Back4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back4,"Back");
lv_obj_set_style_text_color(ui_Back4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back4, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

}
