// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceTemperatureFridgeSetpoint_screen_init(void)
{
ui_ServiceTemperatureFridgeSetpoint = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceTemperatureFridgeSetpoint, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceTemperatureFridgeSetpoint, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceTemperatureFridgeSetpoint, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FridgeManu = lv_label_create(ui_ServiceTemperatureFridgeSetpoint);
lv_obj_set_width( ui_FridgeManu, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FridgeManu, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FridgeManu, 0 );
lv_obj_set_y( ui_FridgeManu, -96 );
lv_obj_set_align( ui_FridgeManu, LV_ALIGN_CENTER );
lv_label_set_text(ui_FridgeManu,"Fridge");
lv_obj_set_style_text_color(ui_FridgeManu, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FridgeManu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_FridgeManu, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FridgeManu, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FridgeManu, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FridgeManu, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetPoint = lv_label_create(ui_ServiceTemperatureFridgeSetpoint);
lv_obj_set_width( ui_SetPoint, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetPoint, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetPoint, -1 );
lv_obj_set_y( ui_SetPoint, -48 );
lv_obj_set_align( ui_SetPoint, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetPoint,"Set Point");
lv_obj_set_style_text_color(ui_SetPoint, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetPoint, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetPoint, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetPoint, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue = lv_label_create(ui_ServiceTemperatureFridgeSetpoint);
lv_obj_set_width( ui_TemperatureValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue, -4 );
lv_obj_set_y( ui_TemperatureValue, 8 );
lv_obj_set_align( ui_TemperatureValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue,"4°C");
lv_obj_set_style_text_color(ui_TemperatureValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back13 = lv_label_create(ui_ServiceTemperatureFridgeSetpoint);
lv_obj_set_width( ui_Back13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back13, -4 );
lv_obj_set_y( ui_Back13, 51 );
lv_obj_set_align( ui_Back13, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back13,"Back");
lv_obj_set_style_text_color(ui_Back13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back13, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
