// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceTemperatureFridgeSetTem_screen_init(void)
{
ui_ServiceTemperatureFridgeSetTem = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceTemperatureFridgeSetTem, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceTemperatureFridgeSetTem, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceTemperatureFridgeSetTem, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_FridgeManu1 = lv_label_create(ui_ServiceTemperatureFridgeSetTem);
lv_obj_set_width( ui_FridgeManu1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_FridgeManu1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_FridgeManu1, 0 );
lv_obj_set_y( ui_FridgeManu1, -96 );
lv_obj_set_align( ui_FridgeManu1, LV_ALIGN_CENTER );
lv_label_set_text(ui_FridgeManu1,"Fridge");
lv_obj_set_style_text_color(ui_FridgeManu1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_FridgeManu1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_FridgeManu1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_FridgeManu1, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_FridgeManu1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_FridgeManu1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetPoint1 = lv_label_create(ui_ServiceTemperatureFridgeSetTem);
lv_obj_set_width( ui_SetPoint1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetPoint1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetPoint1, -1 );
lv_obj_set_y( ui_SetPoint1, -48 );
lv_obj_set_align( ui_SetPoint1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetPoint1,"Set Point");
lv_obj_set_style_text_color(ui_SetPoint1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetPoint1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetPoint1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetPoint1, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue1 = lv_label_create(ui_ServiceTemperatureFridgeSetTem);
lv_obj_set_width( ui_TemperatureValue1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue1, -7 );
lv_obj_set_y( ui_TemperatureValue1, 0 );
lv_obj_set_align( ui_TemperatureValue1, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue1,"4°C");
lv_obj_set_style_text_color(ui_TemperatureValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue2 = lv_label_create(ui_ServiceTemperatureFridgeSetTem);
lv_obj_set_width( ui_TemperatureValue2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue2, -3 );
lv_obj_set_y( ui_TemperatureValue2, 37 );
lv_obj_set_align( ui_TemperatureValue2, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue2,"5°C");
lv_obj_set_style_text_color(ui_TemperatureValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue2, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue3 = lv_label_create(ui_ServiceTemperatureFridgeSetTem);
lv_obj_set_width( ui_TemperatureValue3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue3, -3 );
lv_obj_set_y( ui_TemperatureValue3, 73 );
lv_obj_set_align( ui_TemperatureValue3, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue3,"6°C");
lv_obj_set_style_text_color(ui_TemperatureValue3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
