// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceCalibration_screen_init(void)
{
ui_ServiceCalibration = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceCalibration, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceCalibration, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceCalibration, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Service3 = lv_label_create(ui_ServiceCalibration);
lv_obj_set_width( ui_Service3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Service3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Service3, 0 );
lv_obj_set_y( ui_Service3, -96 );
lv_obj_set_align( ui_Service3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Service3,"Service");
lv_obj_set_style_text_color(ui_Service3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Service3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Service3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Service3, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Service3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Service3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temperature10 = lv_label_create(ui_ServiceCalibration);
lv_obj_set_width( ui_Temperature10, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature10, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature10, -7 );
lv_obj_set_y( ui_Temperature10, -49 );
lv_obj_set_align( ui_Temperature10, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature10,"Temperature");
lv_obj_set_style_text_color(ui_Temperature10, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temperature10, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Temperature10, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temperature10, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alarms8 = lv_label_create(ui_ServiceCalibration);
lv_obj_set_width( ui_Alarms8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Alarms8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Alarms8, -2 );
lv_obj_set_y( ui_Alarms8, -17 );
lv_obj_set_align( ui_Alarms8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Alarms8,"Alarms");
lv_obj_set_style_text_color(ui_Alarms8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Alarms8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Alarms8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Alarms8, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back34 = lv_label_create(ui_ServiceCalibration);
lv_obj_set_width( ui_Back34, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back34, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back34, -10 );
lv_obj_set_y( ui_Back34, 88 );
lv_obj_set_align( ui_Back34, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back34,"Back");
lv_obj_set_style_text_color(ui_Back34, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back34, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back34, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back34, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DataLogging5 = lv_label_create(ui_ServiceCalibration);
lv_obj_set_width( ui_DataLogging5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DataLogging5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DataLogging5, -1 );
lv_obj_set_y( ui_DataLogging5, 13 );
lv_obj_set_align( ui_DataLogging5, LV_ALIGN_CENTER );
lv_label_set_text(ui_DataLogging5,"Data Logging");
lv_obj_set_style_text_color(ui_DataLogging5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DataLogging5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DataLogging5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DataLogging5, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Calibrartion3 = lv_label_create(ui_ServiceCalibration);
lv_obj_set_width( ui_Calibrartion3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Calibrartion3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Calibrartion3, -1 );
lv_obj_set_y( ui_Calibrartion3, 52 );
lv_obj_set_align( ui_Calibrartion3, LV_ALIGN_CENTER );
lv_label_set_text(ui_Calibrartion3,"Calibrartion");
lv_obj_set_style_text_color(ui_Calibrartion3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Calibrartion3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Calibrartion3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Calibrartion3, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

}
