// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsLidEnter_screen_init(void)
{
ui_ServiceAlarmsLidEnter = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsLidEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsLidEnter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsLidEnter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LidAlarm = lv_label_create(ui_ServiceAlarmsLidEnter);
lv_obj_set_width( ui_LidAlarm, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LidAlarm, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LidAlarm, 3 );
lv_obj_set_y( ui_LidAlarm, -78 );
lv_obj_set_align( ui_LidAlarm, LV_ALIGN_CENTER );
lv_label_set_text(ui_LidAlarm,"Lid Alarm");
lv_obj_set_style_text_color(ui_LidAlarm, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LidAlarm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LidAlarm, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LidAlarm, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_LidAlarm, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_LidAlarm, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeValue6 = lv_label_create(ui_ServiceAlarmsLidEnter);
lv_obj_set_width( ui_TimeValue6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeValue6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeValue6, -2 );
lv_obj_set_y( ui_TimeValue6, -1 );
lv_obj_set_align( ui_TimeValue6, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeValue6,"2 mins");
lv_obj_set_style_text_color(ui_TimeValue6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeValue6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeValue6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeValue6, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back24 = lv_label_create(ui_ServiceAlarmsLidEnter);
lv_obj_set_width( ui_Back24, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back24, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back24, -2 );
lv_obj_set_y( ui_Back24, 44 );
lv_obj_set_align( ui_Back24, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back24,"Back");
lv_obj_set_style_text_color(ui_Back24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back24, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back24, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back24, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
