// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsBack_screen_init(void)
{
ui_ServiceAlarmsBack = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsBack, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsBack, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsBack, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alarms6 = lv_label_create(ui_ServiceAlarmsBack);
lv_obj_set_width( ui_Alarms6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Alarms6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Alarms6, 0 );
lv_obj_set_y( ui_Alarms6, -96 );
lv_obj_set_align( ui_Alarms6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Alarms6,"Alarms");
lv_obj_set_style_text_color(ui_Alarms6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Alarms6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Alarms6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Alarms6, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Alarms6, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Alarms6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temperature8 = lv_label_create(ui_ServiceAlarmsBack);
lv_obj_set_width( ui_Temperature8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature8, -8 );
lv_obj_set_y( ui_Temperature8, -54 );
lv_obj_set_align( ui_Temperature8, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature8,"Temperature");
lv_obj_set_style_text_color(ui_Temperature8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temperature8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Temperature8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temperature8, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Battery4 = lv_label_create(ui_ServiceAlarmsBack);
lv_obj_set_width( ui_Battery4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Battery4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Battery4, -2 );
lv_obj_set_y( ui_Battery4, -22 );
lv_obj_set_align( ui_Battery4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Battery4,"Battery");
lv_obj_set_style_text_color(ui_Battery4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Battery4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Battery4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Battery4, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Lid4 = lv_label_create(ui_ServiceAlarmsBack);
lv_obj_set_width( ui_Lid4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Lid4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Lid4, -1 );
lv_obj_set_y( ui_Lid4, 11 );
lv_obj_set_align( ui_Lid4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Lid4,"Lid");
lv_obj_set_style_text_color(ui_Lid4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Lid4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Lid4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Lid4, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back30 = lv_label_create(ui_ServiceAlarmsBack);
lv_obj_set_width( ui_Back30, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back30, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back30, -10 );
lv_obj_set_y( ui_Back30, 83 );
lv_obj_set_align( ui_Back30, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back30,"Back");
lv_obj_set_style_text_color(ui_Back30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back30, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back30, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back30, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MuteAlarms4 = lv_label_create(ui_ServiceAlarmsBack);
lv_obj_set_width( ui_MuteAlarms4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MuteAlarms4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MuteAlarms4, -2 );
lv_obj_set_y( ui_MuteAlarms4, 42 );
lv_obj_set_align( ui_MuteAlarms4, LV_ALIGN_CENTER );
lv_label_set_text(ui_MuteAlarms4,"Mute Alarm");
lv_obj_set_style_text_color(ui_MuteAlarms4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MuteAlarms4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MuteAlarms4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MuteAlarms4, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
