// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsMuteAlarmEnter_screen_init(void)
{
ui_ServiceAlarmsMuteAlarmEnter = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsMuteAlarmEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsMuteAlarmEnter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsMuteAlarmEnter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MuteDuration = lv_label_create(ui_ServiceAlarmsMuteAlarmEnter);
lv_obj_set_width( ui_MuteDuration, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MuteDuration, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MuteDuration, 3 );
lv_obj_set_y( ui_MuteDuration, -78 );
lv_obj_set_align( ui_MuteDuration, LV_ALIGN_CENTER );
lv_label_set_text(ui_MuteDuration,"Mute Duration");
lv_obj_set_style_text_color(ui_MuteDuration, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MuteDuration, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MuteDuration, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MuteDuration, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_MuteDuration, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_MuteDuration, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeValue = lv_label_create(ui_ServiceAlarmsMuteAlarmEnter);
lv_obj_set_width( ui_TimeValue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeValue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeValue, -2 );
lv_obj_set_y( ui_TimeValue, -1 );
lv_obj_set_align( ui_TimeValue, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeValue,"2 mins");
lv_obj_set_style_text_color(ui_TimeValue, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeValue, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeValue, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeValue, &lv_font_montserrat_40, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back28 = lv_label_create(ui_ServiceAlarmsMuteAlarmEnter);
lv_obj_set_width( ui_Back28, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back28, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back28, -2 );
lv_obj_set_y( ui_Back28, 44 );
lv_obj_set_align( ui_Back28, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back28,"Back");
lv_obj_set_style_text_color(ui_Back28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back28, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back28, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back28, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
