// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceCalibrationEnter_screen_init(void)
{
ui_ServiceCalibrationEnter = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceCalibrationEnter, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceCalibrationEnter, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceCalibrationEnter, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Calibrartion4 = lv_label_create(ui_ServiceCalibrationEnter);
lv_obj_set_width( ui_Calibrartion4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Calibrartion4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Calibrartion4, 3 );
lv_obj_set_y( ui_Calibrartion4, -78 );
lv_obj_set_align( ui_Calibrartion4, LV_ALIGN_CENTER );
lv_label_set_text(ui_Calibrartion4,"Calibrartion");
lv_obj_set_style_text_color(ui_Calibrartion4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Calibrartion4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Calibrartion4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Calibrartion4, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Calibrartion4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Calibrartion4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperOffset = lv_label_create(ui_ServiceCalibrationEnter);
lv_obj_set_width( ui_TemperOffset, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperOffset, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperOffset, 3 );
lv_obj_set_y( ui_TemperOffset, -2 );
lv_obj_set_align( ui_TemperOffset, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperOffset,"Temper Offset");
lv_obj_set_style_text_color(ui_TemperOffset, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperOffset, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperOffset, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperOffset, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back35 = lv_label_create(ui_ServiceCalibrationEnter);
lv_obj_set_width( ui_Back35, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back35, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back35, -2 );
lv_obj_set_y( ui_Back35, 44 );
lv_obj_set_align( ui_Back35, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back35,"Back");
lv_obj_set_style_text_color(ui_Back35, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back35, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back35, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back35, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
