// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceDataLogging_screen_init(void)
{
ui_ServiceDataLogging = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceDataLogging, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceDataLogging, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceDataLogging, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Service2 = lv_label_create(ui_ServiceDataLogging);
lv_obj_set_width( ui_Service2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Service2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Service2, 0 );
lv_obj_set_y( ui_Service2, -96 );
lv_obj_set_align( ui_Service2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Service2,"Service");
lv_obj_set_style_text_color(ui_Service2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Service2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Service2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Service2, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Service2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Service2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Temperature9 = lv_label_create(ui_ServiceDataLogging);
lv_obj_set_width( ui_Temperature9, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Temperature9, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Temperature9, -7 );
lv_obj_set_y( ui_Temperature9, -49 );
lv_obj_set_align( ui_Temperature9, LV_ALIGN_CENTER );
lv_label_set_text(ui_Temperature9,"Temperature");
lv_obj_set_style_text_color(ui_Temperature9, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Temperature9, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Temperature9, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Temperature9, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Alarms7 = lv_label_create(ui_ServiceDataLogging);
lv_obj_set_width( ui_Alarms7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Alarms7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Alarms7, -2 );
lv_obj_set_y( ui_Alarms7, -17 );
lv_obj_set_align( ui_Alarms7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Alarms7,"Alarms");
lv_obj_set_style_text_color(ui_Alarms7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Alarms7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Alarms7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Alarms7, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back31 = lv_label_create(ui_ServiceDataLogging);
lv_obj_set_width( ui_Back31, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back31, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back31, -10 );
lv_obj_set_y( ui_Back31, 86 );
lv_obj_set_align( ui_Back31, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back31,"Back");
lv_obj_set_style_text_color(ui_Back31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back31, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back31, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back31, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DataLogging2 = lv_label_create(ui_ServiceDataLogging);
lv_obj_set_width( ui_DataLogging2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DataLogging2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DataLogging2, -1 );
lv_obj_set_y( ui_DataLogging2, 16 );
lv_obj_set_align( ui_DataLogging2, LV_ALIGN_CENTER );
lv_label_set_text(ui_DataLogging2,"Data Logging");
lv_obj_set_style_text_color(ui_DataLogging2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DataLogging2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DataLogging2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DataLogging2, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Calibrartion2 = lv_label_create(ui_ServiceDataLogging);
lv_obj_set_width( ui_Calibrartion2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Calibrartion2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Calibrartion2, -1 );
lv_obj_set_y( ui_Calibrartion2, 54 );
lv_obj_set_align( ui_Calibrartion2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Calibrartion2,"Calibrartion");
lv_obj_set_style_text_color(ui_Calibrartion2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Calibrartion2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Calibrartion2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Calibrartion2, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
