// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsLidSet_screen_init(void)
{
ui_ServiceAlarmsLidSet = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsLidSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsLidSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsLidSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatteryAlarm3 = lv_label_create(ui_ServiceAlarmsLidSet);
lv_obj_set_width( ui_BatteryAlarm3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryAlarm3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryAlarm3, -5 );
lv_obj_set_y( ui_BatteryAlarm3, -78 );
lv_obj_set_align( ui_BatteryAlarm3, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatteryAlarm3,"Battery Alarm");
lv_obj_set_style_text_color(ui_BatteryAlarm3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatteryAlarm3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BatteryAlarm3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatteryAlarm3, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeValue3 = lv_label_create(ui_ServiceAlarmsLidSet);
lv_obj_set_width( ui_TimeValue3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeValue3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeValue3, -6 );
lv_obj_set_y( ui_TimeValue3, -10 );
lv_obj_set_align( ui_TimeValue3, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeValue3,"3 mins");
lv_obj_set_style_text_color(ui_TimeValue3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeValue3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeValue3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeValue3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeValue4 = lv_label_create(ui_ServiceAlarmsLidSet);
lv_obj_set_width( ui_TimeValue4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeValue4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeValue4, -3 );
lv_obj_set_y( ui_TimeValue4, 30 );
lv_obj_set_align( ui_TimeValue4, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeValue4,"2 mins");
lv_obj_set_style_text_color(ui_TimeValue4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeValue4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeValue4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeValue4, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeValue5 = lv_label_create(ui_ServiceAlarmsLidSet);
lv_obj_set_width( ui_TimeValue5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeValue5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeValue5, -2 );
lv_obj_set_y( ui_TimeValue5, 68 );
lv_obj_set_align( ui_TimeValue5, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeValue5,"1 mins");
lv_obj_set_style_text_color(ui_TimeValue5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeValue5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeValue5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeValue5, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
