// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsMuteAlarmSet_screen_init(void)
{
ui_ServiceAlarmsMuteAlarmSet = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsMuteAlarmSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsMuteAlarmSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsMuteAlarmSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_MuteDuration1 = lv_label_create(ui_ServiceAlarmsMuteAlarmSet);
lv_obj_set_width( ui_MuteDuration1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_MuteDuration1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_MuteDuration1, -5 );
lv_obj_set_y( ui_MuteDuration1, -78 );
lv_obj_set_align( ui_MuteDuration1, LV_ALIGN_CENTER );
lv_label_set_text(ui_MuteDuration1,"Mute Duration");
lv_obj_set_style_text_color(ui_MuteDuration1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_MuteDuration1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_MuteDuration1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_MuteDuration1, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeValue1 = lv_label_create(ui_ServiceAlarmsMuteAlarmSet);
lv_obj_set_width( ui_TimeValue1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeValue1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeValue1, -6 );
lv_obj_set_y( ui_TimeValue1, -10 );
lv_obj_set_align( ui_TimeValue1, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeValue1,"3 mins");
lv_obj_set_style_text_color(ui_TimeValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeValue1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeValue1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeValue7 = lv_label_create(ui_ServiceAlarmsMuteAlarmSet);
lv_obj_set_width( ui_TimeValue7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeValue7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeValue7, -3 );
lv_obj_set_y( ui_TimeValue7, 30 );
lv_obj_set_align( ui_TimeValue7, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeValue7,"2 mins");
lv_obj_set_style_text_color(ui_TimeValue7, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeValue7, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeValue7, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeValue7, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeValue8 = lv_label_create(ui_ServiceAlarmsMuteAlarmSet);
lv_obj_set_width( ui_TimeValue8, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeValue8, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeValue8, -2 );
lv_obj_set_y( ui_TimeValue8, 68 );
lv_obj_set_align( ui_TimeValue8, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeValue8,"1 mins");
lv_obj_set_style_text_color(ui_TimeValue8, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeValue8, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TimeValue8, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeValue8, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
