// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_SettingDateTimeMonth_screen_init(void)
{
ui_SettingDateTimeMonth = lv_obj_create(NULL);
lv_obj_clear_flag( ui_SettingDateTimeMonth, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_SettingDateTimeMonth, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_SettingDateTimeMonth, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetYear1 = lv_label_create(ui_SettingDateTimeMonth);
lv_obj_set_width( ui_SetYear1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetYear1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetYear1, 2 );
lv_obj_set_y( ui_SetYear1, -85 );
lv_obj_set_align( ui_SetYear1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetYear1,"Set Year: 2023");
lv_obj_set_style_text_color(ui_SetYear1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetYear1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetYear1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetYear1, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetMonth1 = lv_label_create(ui_SettingDateTimeMonth);
lv_obj_set_width( ui_SetMonth1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetMonth1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetMonth1, 0 );
lv_obj_set_y( ui_SetMonth1, -50 );
lv_obj_set_align( ui_SetMonth1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetMonth1,"Set Month: 06");
lv_obj_set_style_text_color(ui_SetMonth1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetMonth1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetMonth1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetMonth1, &ui_font_verdana404, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetDay1 = lv_label_create(ui_SettingDateTimeMonth);
lv_obj_set_width( ui_SetDay1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetDay1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetDay1, 0 );
lv_obj_set_y( ui_SetDay1, -13 );
lv_obj_set_align( ui_SetDay1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetDay1,"Set Day: 06");
lv_obj_set_style_text_color(ui_SetDay1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetDay1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetDay1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetDay1, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Back6 = lv_label_create(ui_SettingDateTimeMonth);
lv_obj_set_width( ui_Back6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Back6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Back6, -8 );
lv_obj_set_y( ui_Back6, 84 );
lv_obj_set_align( ui_Back6, LV_ALIGN_CENTER );
lv_label_set_text(ui_Back6,"Back");
lv_obj_set_style_text_color(ui_Back6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_Back6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_Back6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Back6, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetHour1 = lv_label_create(ui_SettingDateTimeMonth);
lv_obj_set_width( ui_SetHour1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetHour1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetHour1, -4 );
lv_obj_set_y( ui_SetHour1, 19 );
lv_obj_set_align( ui_SetHour1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetHour1,"Set Hour: 06");
lv_obj_set_style_text_color(ui_SetHour1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetHour1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetHour1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetHour1, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SetMinute1 = lv_label_create(ui_SettingDateTimeMonth);
lv_obj_set_width( ui_SetMinute1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_SetMinute1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_SetMinute1, -3 );
lv_obj_set_y( ui_SetMinute1, 52 );
lv_obj_set_align( ui_SetMinute1, LV_ALIGN_CENTER );
lv_label_set_text(ui_SetMinute1,"Set Minute: 06");
lv_obj_set_style_text_color(ui_SetMinute1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_SetMinute1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_SetMinute1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_SetMinute1, &ui_font_verdana244, LV_PART_MAIN| LV_STATE_DEFAULT);

}
