// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceAlarmsBatteryAlarmSet_screen_init(void)
{
ui_ServiceAlarmsBatteryAlarmSet = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceAlarmsBatteryAlarmSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceAlarmsBatteryAlarmSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceAlarmsBatteryAlarmSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatteryAlarm1 = lv_label_create(ui_ServiceAlarmsBatteryAlarmSet);
lv_obj_set_width( ui_BatteryAlarm1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatteryAlarm1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatteryAlarm1, -5 );
lv_obj_set_y( ui_BatteryAlarm1, -78 );
lv_obj_set_align( ui_BatteryAlarm1, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatteryAlarm1,"Battery Alarm");
lv_obj_set_style_text_color(ui_BatteryAlarm1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatteryAlarm1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BatteryAlarm1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatteryAlarm1, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatValue1 = lv_label_create(ui_ServiceAlarmsBatteryAlarmSet);
lv_obj_set_width( ui_BatValue1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatValue1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatValue1, -6 );
lv_obj_set_y( ui_BatValue1, -10 );
lv_obj_set_align( ui_BatValue1, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatValue1,"20%");
lv_obj_set_style_text_color(ui_BatValue1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatValue1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BatValue1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatValue1, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatValue2 = lv_label_create(ui_ServiceAlarmsBatteryAlarmSet);
lv_obj_set_width( ui_BatValue2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatValue2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatValue2, -3 );
lv_obj_set_y( ui_BatValue2, 30 );
lv_obj_set_align( ui_BatValue2, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatValue2,"15%");
lv_obj_set_style_text_color(ui_BatValue2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatValue2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BatValue2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatValue2, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BatValue3 = lv_label_create(ui_ServiceAlarmsBatteryAlarmSet);
lv_obj_set_width( ui_BatValue3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_BatValue3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_BatValue3, -2 );
lv_obj_set_y( ui_BatValue3, 68 );
lv_obj_set_align( ui_BatValue3, LV_ALIGN_CENTER );
lv_label_set_text(ui_BatValue3,"10%");
lv_obj_set_style_text_color(ui_BatValue3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_BatValue3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_BatValue3, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_BatValue3, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
