// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceDataLoggingIntervalSet_screen_init(void)
{
ui_ServiceDataLoggingIntervalSet = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceDataLoggingIntervalSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceDataLoggingIntervalSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceDataLoggingIntervalSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LoggingInterval1 = lv_label_create(ui_ServiceDataLoggingIntervalSet);
lv_obj_set_width( ui_LoggingInterval1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LoggingInterval1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LoggingInterval1, -6 );
lv_obj_set_y( ui_LoggingInterval1, -71 );
lv_obj_set_align( ui_LoggingInterval1, LV_ALIGN_CENTER );
lv_label_set_text(ui_LoggingInterval1,"Logging Interval");
lv_obj_set_style_text_color(ui_LoggingInterval1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LoggingInterval1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_LoggingInterval1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LoggingInterval1, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DelayTime4 = lv_label_create(ui_ServiceDataLoggingIntervalSet);
lv_obj_set_width( ui_DelayTime4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DelayTime4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DelayTime4, -7 );
lv_obj_set_y( ui_DelayTime4, 0 );
lv_obj_set_align( ui_DelayTime4, LV_ALIGN_CENTER );
lv_label_set_text(ui_DelayTime4,"4 mins");
lv_obj_set_style_text_color(ui_DelayTime4, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DelayTime4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DelayTime4, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DelayTime4, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DelayTime5 = lv_label_create(ui_ServiceDataLoggingIntervalSet);
lv_obj_set_width( ui_DelayTime5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DelayTime5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DelayTime5, -3 );
lv_obj_set_y( ui_DelayTime5, 37 );
lv_obj_set_align( ui_DelayTime5, LV_ALIGN_CENTER );
lv_label_set_text(ui_DelayTime5,"3 mins");
lv_obj_set_style_text_color(ui_DelayTime5, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DelayTime5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DelayTime5, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DelayTime5, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DelayTime6 = lv_label_create(ui_ServiceDataLoggingIntervalSet);
lv_obj_set_width( ui_DelayTime6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DelayTime6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DelayTime6, -3 );
lv_obj_set_y( ui_DelayTime6, 73 );
lv_obj_set_align( ui_DelayTime6, LV_ALIGN_CENTER );
lv_label_set_text(ui_DelayTime6,"2 mins");
lv_obj_set_style_text_color(ui_DelayTime6, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DelayTime6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_DelayTime6, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_DelayTime6, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
