// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: SquareLine_Project

#include "../ui.h"

void ui_ServiceCalibrationEnterSet_screen_init(void)
{
ui_ServiceCalibrationEnterSet = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ServiceCalibrationEnterSet, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_ServiceCalibrationEnterSet, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ServiceCalibrationEnterSet, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperOffset1 = lv_label_create(ui_ServiceCalibrationEnterSet);
lv_obj_set_width( ui_TemperOffset1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperOffset1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperOffset1, -6 );
lv_obj_set_y( ui_TemperOffset1, -71 );
lv_obj_set_align( ui_TemperOffset1, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperOffset1,"Temper Offset");
lv_obj_set_style_text_color(ui_TemperOffset1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperOffset1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperOffset1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperOffset1, &ui_font_verdana364, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue13 = lv_label_create(ui_ServiceCalibrationEnterSet);
lv_obj_set_width( ui_TemperatureValue13, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue13, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue13, -7 );
lv_obj_set_y( ui_TemperatureValue13, 0 );
lv_obj_set_align( ui_TemperatureValue13, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue13,"4°C");
lv_obj_set_style_text_color(ui_TemperatureValue13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue13, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue13, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue13, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue14 = lv_label_create(ui_ServiceCalibrationEnterSet);
lv_obj_set_width( ui_TemperatureValue14, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue14, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue14, -3 );
lv_obj_set_y( ui_TemperatureValue14, 37 );
lv_obj_set_align( ui_TemperatureValue14, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue14,"3°C");
lv_obj_set_style_text_color(ui_TemperatureValue14, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue14, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue14, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue14, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TemperatureValue15 = lv_label_create(ui_ServiceCalibrationEnterSet);
lv_obj_set_width( ui_TemperatureValue15, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TemperatureValue15, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TemperatureValue15, -3 );
lv_obj_set_y( ui_TemperatureValue15, 73 );
lv_obj_set_align( ui_TemperatureValue15, LV_ALIGN_CENTER );
lv_label_set_text(ui_TemperatureValue15,"2°C");
lv_obj_set_style_text_color(ui_TemperatureValue15, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TemperatureValue15, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_align(ui_TemperatureValue15, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TemperatureValue15, &lv_font_montserrat_24, LV_PART_MAIN| LV_STATE_DEFAULT);

}
